### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OHsEIp/notebook/

### ISSUE THREAD

**Issue by lukaspistelak** [isl-org/Open3D#1361]
```
lukas@lukas-Aspire-E5-571:~/workspace/AnamolyDetection/Size_Me/SizeTube$ sudo pip install --user open3d
The directory '/home/lukas/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/lukas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting open3d
  Downloading https://files.pythonhosted.org/packages/99/e7/63e323ea0b8701c7af09c256e6b85565fedd7ff33f61296d8a86ae863095/open3d-0.8.0.0-cp27-cp27mu-manylinux1_x86_64.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 259kB/s 
Collecting widgetsnbextension (from open3d)
  Downloading https://files.pythonhosted.org/packages/6c/7b/7ac231c20d2d33c445eaacf8a433f4e22c60677eb9776c7c5262d7ddee2d/widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 323kB/s 
Collecting ipywidgets (from open3d)
  Downloading https://files.pythonhosted.org/packages/56/a0/dbcf5881bb2f51e8db678211907f16ea0a182b232c591a6d6f276985ca95/ipywidgets-7.5.1-py2.py3-none-any.whl (121kB)
    100% |████████████████████████████████| 122kB 2.8MB/s 
Collecting notebook (from open3d)
  Downloading https://files.pythonhosted.org/packages/00/53/ff1a170de7aac78fee182e8de12c8ab53c17810654a75393e345c173a118/notebook-6.0.2.tar.gz (14.1MB)
    100% |████████████████████████████████| 14.1MB 43kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-OHsEIp/notebook/setup.py", line 42
        print(error, file=sys.stderr)
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OHsEIp/notebook/
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by airfield20** [comment]
Im also having this issue.

**Comment by swinterbotix** [comment]
Having this issue as well...

**Comment by emosGambler** [comment]
Console says what to do

`pip install --upgrade pip`
