### ISSUE TITLE
Failed to find service port for display

### ISSUE THREAD

**Issue by TimingSpace** [isl-org/Open3D#1673]
**Describe the bug**
On mac OS,10.15.1  `Failed to find service port for display` when trying to visualize a ply file.

**To Reproduce**
`xzy = np.random.random((100,3))*10`
`pcd = o3d.geometry.PointCloud()`
`pcd.points = o3d.utility.Vector3dVector(xyz)`
`o3d.visualization.draw_geometries([pcd])`

then 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: [Open3D ERROR] GLFW Error: Cocoa: Failed to find service port for display
```

**Expected behavior**
Expected to visualize the point cloud

**Environment (please complete the following information):**
 - OS: [ OSX Catalina]
 - Python version: 3.7.3
 - Open3D version:0.9.00
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by keithahern** [comment]
I am running a Macbook with a second display provided by airplaying to an iPad (new OS X feature).  When I disconnected the airplay display I no longer got this error.

**Comment by ruoyuwangeel4930** [comment]
Hello, do you fix the problem now?

**Comment by Jianghanxiao** [comment]
I also meet the problem on mac M1

**Comment by Ao-senXiong** [comment]
Did anyone ever success this on mac M1? It troubles me!!! 
Thx!!!

**Comment by adityamwagh** [comment]
Has anyone been able to fix this on an M1 MacBook?

**Comment by Jianghanxiao** [comment]
> Has anyone been able to fix this on an M1 MacBook?

I remember use the latest open3D can solve the problem

**Comment by adityamwagh** [comment]
@Jianghanxiao Do you remember how you did it? I had compiled Open3D v0.13.0, but still the visualizations didn't show up and neither the point cloud data was read.

**Comment by Jianghanxiao** [comment]
> @Jianghanxiao Do you remember how you did it? I had compiled Open3D v0.13.0, but still the visualizations didn't show up and neither the point cloud data was read.

Based on my current environment, the open3D I use is 0.12.0. It's installed through pip

**Comment by adityamwagh** [comment]
Can you import a pcd file, and then show me the visualization?

**Comment by DenisTome** [comment]
I'm having the same issue on a M1 Max with 0.14.1 installed though pip

**Comment by errissa** [comment]
@DenisTome Please try the development pip packages available [here](http://www.open3d.org/docs/release/getting_started.html). Some fixes have been made since 0.14.1 to support Apple Silicon (M1).

**Comment by adityamwagh** [comment]
They have changed how the visualizer is accessed in 0.14.0. Try the new one @DenisTome.

**Comment by YajJackson** [comment]
Tested with 0.15.1.
Calling both: `open3d.visualization.draw_geometries` and `open3d.visualization.draw` raise:
```
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
```

The GUI opens, but displays an empty scene:
<img width="955" alt="Screen Shot 2022-06-15 at 3 00 00 PM" src="https://user-images.githubusercontent.com/19982913/173904306-b626cf91-5d0e-4d40-a4c5-867fe1c85262.png">

**Comment by maurock** [comment]
@YajJackson I had a similar issue, then noticed that the object is actually there but you need to rotate the viewport to see it (left click + move your mouse/zoom in-out until you see something). My guess is that it does not render properly when normals are aligned in certain directions. Setting `mesh_show_wireframe=True` in `o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True)` helps, in the sense that you can see the mesh wireframe so the object becomes more visibile even for small meshes.

**Comment by nono-zz** [comment]
> Tested with 0.15.1. Calling both: `open3d.visualization.draw_geometries` and `open3d.visualization.draw` raise:
> 
> ```
> [Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
> ```
> 
> The GUI opens, but displays an empty scene: <img alt="Screen Shot 2022-06-15 at 3 00 00 PM" width="955" src="https://user-images.githubusercontent.com/19982913/173904306-b626cf91-5d0e-4d40-a4c5-867fe1c85262.png">

Same problem here

**Comment by tsenguunchik** [comment]
Any update on this? Running M2 Macbook air

**Comment by schauppi** [comment]
Same issue on Mac M1. open3d 0.11.2 and python 3.8.13.

**Comment by adityamwagh** [comment]
@schauppi Update to Open3D 0.15.1, your version doesn't have support for Apple Silicon.

**Comment by adityamwagh** [comment]
@azadeh-sharafi Experiment with a newer version of Python and also try using `open3d v0.15.1`

**Comment by xbbkok** [comment]
I meet the problem on mac M2

**Comment by siyanhu** [comment]
me too. on MacOS Ventura 13.1, Apple M1

**Comment by LouisSY** [comment]
I created a Conda env with x86 architecture on my m1 Mac and I also have this problem.

Environment:

OS: macOS Ventura 13.2
Python version: 3.9.15, arch=x86_64
Open3D version:0.16.1
Is this remote workstation?: no
How did you install Open3D?: pip

**Comment by Hiusam** [comment]
Me too. With M1 Pro, python=3.9, and open3d 0.15.1

**Comment by rwijmashell** [comment]
Was having this issue as well. I noticed that switching from ```draw_geometries``` to simply using the new ```draw``` fixed my issues.

**Comment by Sergeytata** [comment]
Same problem M1 Pro; Open3d 0.17.0

**Comment by jiazhou2023** [comment]
Same issue.

**Comment by bedbad** [comment]
Problem persists

**Comment by siyanhu** [comment]
same here for my M1 laptop. I have to switch to intel Mac right now temporarily.

**Comment by prerakmody** [comment]
I am using `open3d==0.17.0` on a Macbook M1 with `python==3.9.12` and am able to view the visualizer with `o3d.visualization.draw_geometries([pcd])`

But I still get the error `[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display`.

Also, if I close the visualizer and run more code (while inside a python interpreter), it hangs and gives the following error
```
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] [PhongShaderForTriangleMesh] Compiling shaders failed.
```

Then I have to restart the terminal again which slows down my debugging process.

**Comment by cwreynolds** [comment]
Sorry that this is no help to the people still seeing this problem, but for whatever help it is to isolate the cause: 

I’m able to run **Open3D 0.17.0** without these problems, using **macOS Monterey 12.6.4** on a **2021 MacBook Pro M1 Max**. I’m using **Python 3.10.10** via a Conda environment. In case it is relevant, I installed GLEW and GLFW via Homebrew, for use from c++, in the last few months.

I’m able to use `o3d.visualization.draw_geometries()` as in the original test code for this issue. Normally I use the “non blocking” API `o3d.visualization.Visualizer()`, `update_geometry()`, etc. I’ve also run the newer `o3d.visualization.draw()` tools.

I do see this message once: “[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display” but everything seem to work OK.

**Comment by OHNOalan** [comment]
Encounter following bug using GLFW "0.52.0" with rust version "1.26.0" on macOS 13.4.1 with 2021 Apple M1 Pro Chip.

Bug Info: "thread 'main' panicked at 'GLFW Error: Cocoa: Failed to find service port for display'"

**Comment by imxtx** [comment]
same problem with M2 Pro Mac mini.

**Comment by sanikeit** [comment]
same issue with Mac M1 pro

**Comment by jayyoung0802** [comment]
same problem with M2 pro

**Comment by MaureenZOU** [comment]
+1

**Comment by robinthibaut** [comment]
+1

**Comment by LJHG** [comment]
same problem on m1 pro

**Comment by mxagar** [comment]
Same problem here on my Apple MacBook Pro M1 (Sonoma 14.4.1).

I noticed that the latest Open3D version I can install using pip is 0.16.1, not the latest release 0.18. If I try to manually install the 0.18 release wheels I get system compatibility errors; e.g.:

$ pip install https://github.com/isl-org/Open3D/releases/download/v0.18.0/open3d-0.18.0-cp310-cp310-macosx_13_0_arm64.whl

--> ERROR: open3d-0.18.0-cp310-cp310-macosx_13_0_arm64.whl is not a supported wheel on this platform.

I suspect one could build Open3D locally on the machine or using docker to get the latest working wheels...

**Comment by LaFerraille** [comment]
Same issue here for Mac M2, any updates ?

**Comment by jasonbian97** [comment]
Same issue for MacBookPro M2.

**Comment by gdudek** [comment]
Same problem with open3d 0.18.0
M3 Pro
Sonoma 14.4

**Comment by benjaminhr** [comment]
same problem here

**Comment by yc4ny** [comment]
same problem here
M2 AIR 
Sonoma 14.6.1

**Comment by zhuhu00** [comment]
Omg, same problem, 
M3 Pro, Sequoia 15.0

**Comment by henryrobbins** [comment]
Same problem:
* Open3D 0.18.0 (built from source)
* M3 Pro
* Sequoia 15.0

**Comment by siyanhu** [comment]
I'm glad that MacOS keeps making trouble to Open3D. Love this phenomenon. Should have installed a linux.

**Comment by iballester** [comment]
Has anyone found a solution?

**Comment by ansj11** [comment]
I also has the same problem and a "ValueError: vector" error, does anyone solve this problem?

`Mesh does not have texture. Loading texture manually...
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
2025-03-26 21:15:26.357 Python[31897:2310087] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Traceback (most recent call last):
  File "/Users/anshijie/git/visualize/main.py", line 719, in <module>
    vis3d.run()
  File "/Users/anshijie/git/visualize/main.py", line 327, in run
    o3d.visualization.draw_geometries_with_key_callbacks(obj_list, key_to_callback)
ValueError: vector`
