### ISSUE TITLE
Problems building a working python package with CUDA on Windows

### ISSUE THREAD

**Issue by cdrose** [isl-org/Open3D#3827]
I see from past issues that CUDA on Windows was not supported until recently, is this configuration expected to work? Any ideas what might have gone wrong and what I need to change to fix it?

I am running Python 3.8 and CUDA 11.1 on Windows 10, the build process appears to complete normally and builds the wheel. On 'import open3d' I get:

`Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Projects\Open3D\venv\lib\site-packages\open3d\__init__.py", line 75, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'`

From putting some debug prints into __init__.py it fails with an OSError implying CUDA is not installed.

`try:
        # Check CUDA availability without importing CUDA pybind symbols to
        # prevent "symbol already registered" errors if first import fails.
        print(str(next((_Path(__file__).parent / 'cuda').glob('pybind*'))))
        _pybind_cuda = _CDLL(
            str(next((_Path(__file__).parent / 'cuda').glob('pybind*'))))
        print(_pybind_cuda.open3d_core_cuda_device_count())
        if _pybind_cuda.open3d_core_cuda_device_count() > 0:
            from open3d.cuda.pybind import (camera, geometry, io, pipelines,
                                            utility, t)
            from open3d.cuda import pybind
            __DEVICE_API__ = 'cuda'
    except OSError:  # CUDA not installed
        print("CUDA not installed")
    except StopIteration:  # pybind cuda library not available
        print("pybind cuda library not available")`

The CDLL path it is checking looks a little suspicious being marked cp39 not cp38
"D:\Projects\Open3D\venv\lib\site-packages\open3d\cuda\pybind.cp39-win_amd64.pyd"

**Comment by ssheorey** [comment]
HI @cdrose in your cmake build configuration, check that you are using Python 3.8 during building. (`cmake-gui` is pretty helpful). Looks like the build process used Python 3.9, which is not available when you do `import open3d`.

**Comment by cdrose** [comment]
The PYTHON_EXECUTABLE is correctly showing Python38, is there somewhere else to check also?

**Comment by cdrose** [comment]
Is this warning from the build output of any relevance?

```
Creating library D:/Projects/Open3D/Open3D-master/build/lib/Release/Python/cuda/pybind.lib and object D:/Projects/
  Open3D/Open3D-master/build/lib/Release/Python/cuda/pybind.exp
D:\Projects\Open3D\Open3D-master\build\lib\Release\Python\cuda\pybind.cp39-win_amd64.pyd : warning LNK4088: image being
 generated due to /FORCE option; image may not run [D:\Projects\Open3D\Open3D-master\build\cpp\pybind\pybind.vcxproj]
  Generating code
  Finished generating code
```

**Comment by ssheorey** [comment]
> The PYTHON_EXECUTABLE is correctly showing Python38, is there somewhere else to check also?
> 
> Are Python 3.9 and CUDA 11.3 supported? I originally had Python 3.9 and CUDA 11.3 installed but removed them and went back to 11.1 and 3.8 before attempting to build Open3D as the docs didnt list them as being supported.

Yes, Python 3.6-3.9 and CUDA 10.1+ (including 11.3) are supported in `master`. (Make sure the version of the docs that you refer matches the version of the code that you use.)

We use `CMake` `FindPython` to pick up the Python version, which may sometimes pick up the incorrect one, based on your environment. Check the `CMake` documentation here:

https://cmake.org/cmake/help/v3.19/module/FindPython.html#hints

This page also lists `CMake` Python related variables that should be in your `cmake-gui`. Check that they all point to the correct Python version. `PYTHON_EXECUTABLE` is deprecated but used by some 3rd party modules.

**Comment by ssheorey** [comment]
Also, if you use something like `pyenv` to set your Python version per directory, **all subfolders** of your build folder must have the same Python version / virtual environment.

**Comment by cdrose** [comment]
Thanks so much for your help with this. I have to spend some time on another project for a bit but I'll be back to this on Monday and will try your suggestions.

**Comment by AustinMooreT** [comment]
I'm having similar issues building on windows. Is there any information I can provide to help?

**Comment by tostercx** [comment]
Just wasted the whole day on a similar issue

    ModuleNotFoundError: No module named 'open3d.cpu'

Turns out that the python module can't find CUDA dlls for some reason

![image](https://user-images.githubusercontent.com/4965387/129367485-9c3a48b7-829a-4c43-beaa-fa6fa6a5f246.png)

Even tho they are in PATH!

    >where cusolver64_10.dll
    C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cusolver64_10.dll

Not sure if it's a python thing or what... copying all the dlls to my python dir solved it.

**Comment by ssheorey** [comment]
Python 3.8+ no longer uses PATH to look for DLLs.
https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew

PR #3817 uses static CUDA libraries on Linux to avoid this issue, but Windows static CUDA libraries are not available.
PR #3918 adds explicit warnings to help debugging these issues.

**Comment by reyanshsolis** [comment]
Closing the issue as resolved.
