### ISSUE TITLE
O3DVisualiser crashes if you call AddGeometry() with a pointcloud containing 1 point

### ISSUE THREAD

**Issue by willat343** [isl-org/Open3D#3967]
**Describe the bug**
O3DVisualiser crashes when a pointcloud containing exactly 1 point is added, with the following output:
```
N5utils18PostconditionPanicE
in RenderableManager::Builder::Result filament::RenderableManager::Builder::build(filament::Engine &, utils::Entity):236
reason: [entity=51] AABB can't be empty, unless culling is disabled and the object is not a shadow caster/receiver
#0      o3d_bug                             0x55a57861a210 (null) + 94169177629200
#1      o3d_bug                             0x55a57856d521 (null) + 94169176921377
#2      o3d_bug                             0x55a5782dd6fc (null) + 94169174234876
#3      o3d_bug                             0x55a5782de5f0 (null) + 94169174238704
#4      o3d_bug                             0x55a57822661f (null) + 94169173485087
#5      o3d_bug                             0x55a5782172b4 (null) + 94169173422772
#6      o3d_bug                             0x55a578207f0d (null) + 94169173360397
#7      o3d_bug                             0x55a5781b31d9 (null) + 94169173012953
#8      libc.so.6                           0x7fca38ee5bf7 __libc_start_main + 231


terminate called after throwing an instance of 'utils::PostconditionPanic'
Aborted (core dumped)
```

No crash occurs if the pointcloud is of size 2 or 1000, and if size 0, a warning is produced but no crash (`[Open3D WARNING] Geometry pointcloud is not in the scene graph`).

**To Reproduce**
I have attached a main and CMakeLists.txt as a minimal reproducible example. I have added the 0-point, 2-point and 1000-point tests which all work as expected as comments.

_NOTE: rename main.txt to main.cpp (github does not allow uploading .cpp files in issues)_

[CMakeLists.txt](https://github.com/isl-org/Open3D/files/7031060/CMakeLists.txt)
[main.txt](https://github.com/isl-org/Open3D/files/7031062/main.txt)

**Expected behavior**
No crash should occur when a pointcloud of size 1 is added.

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Open3D version: 0.13
- Is this remote workstation?: yes or no
- How did you install Open3D?: built from source at tag v0.13.0
- Compiler version (if built from source): gcc 7.5

**Additional context**
I have built in debug mode and run with `gdb` (with following stacktrace), and the crash produces the attached stack trace.
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g" -DCMAKE_C_FLAGS="-g" ..
make
gdb o3d_bug
(gdb) r
...
(gdb) bt
```

Stack trace using gdb:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6291921 in __GI_abort () at abort.c:79
#2  0x00007ffff7480957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7486ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7486b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7486d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555af0329 in utils::TPanic<utils::PostconditionPanic>::panic(char const*, char const*, int, char const*, ...) ()
#7  0x0000555555a43521 in filament::RenderableManager::Builder::build(filament::Engine&, utils::Entity) ()
#8  0x00005555557b36fc in open3d::visualization::rendering::FilamentScene::CreateAndAddFilamentEntity (this=this@entry=0x55555b540850, object_name="pointcloud", 
    buffer_builder=..., aabb=..., vb=..., ib=..., material=..., reusing_vertex_buffer=open3d::visualization::rendering::FilamentScene::kNo)
    at /opt/open3d/cpp/open3d/visualization/rendering/filament/FilamentScene.cpp:526
#9  0x00005555557b45f0 in open3d::visualization::rendering::FilamentScene::AddGeometry (this=0x55555b540850, object_name="pointcloud", geometry=..., material=..., 
    downsampled_name="pointcloud.__fast__", downsample_threshold=<optimised out>) at /opt/open3d/cpp/open3d/visualization/rendering/filament/FilamentScene.cpp:362
#10 0x00005555556fc61f in open3d::visualization::rendering::Open3DScene::AddGeometry (this=0x55555b540f50, name="pointcloud", geom=0x55555b7b7c60, mat=..., 
    add_downsampled_copy_for_fast_rendering=add_downsampled_copy_for_fast_rendering@entry=true)
    at /opt/open3d/cpp/open3d/visualization/rendering/Open3DScene.cpp:266
#11 0x00005555556ed2b4 in open3d::visualization::visualizer::O3DVisualizer::Impl::AddGeometry (this=0x55555aa98820, name="pointcloud", 
    geom=std::shared_ptr<open3d::geometry::Geometry3D> (use count 4, weak count 0) = {...}, tgeom=std::shared_ptr<open3d::t::geometry::Geometry> (empty) = {...}, 
    model=std::shared_ptr<open3d::visualization::rendering::TriangleMeshModel> (empty) = {...}, material=<optimised out>, group="", time=0, is_visible=true)
    at /opt/open3d/cpp/open3d/visualization/visualizer/O3DVisualizer.cpp:978
#12 0x00005555556ddf0d in open3d::visualization::visualizer::O3DVisualizer::AddGeometry (this=<optimised out>, name=..., geom=..., material=<optimised out>, 
    group=..., time=<optimised out>, is_visible=<optimised out>) at /opt/open3d/cpp/open3d/visualization/visualizer/O3DVisualizer.cpp:1942
#13 0x00005555556891d9 in main (argc=1, argv=0x7fffffffcdd8) at /home/williamtalbot/src/personal/o3dvis_1point_bug/main.cpp:23
```

**Comment by nicholas-p1** [comment]
I have the same problem.
