### ISSUE TITLE
Compile from source and allow import from cuda and cpu module

### ISSUE THREAD

**Issue by maxim0815** [isl-org/Open3D#4371]
**Describe the bug**
I followed the [description](http://www.open3d.org/docs/release/compilation.html#compilation) to build Open3D with Open3D-ML from source including python and pytorch modules within an Docker environment:

```
git clone --recursive https://github.com/intel-isl/Open3D 
cd Open3D \
git submodule update --init --recursive 
git clone https://github.com/intel-isl/Open3D-ML 
util/install_deps_ubuntu.sh assume-yes 
mkdir build 
cd build 
cmake \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_CUDA_MODULE=ON \
        -DBUILD_PYTORCH_OPS=ON \
        -DBUILD_TENSORFLOW_OPS=OFF \
        -DPYTHON_EXECUTABLE=$(which python) \
        -DBUILD_PYTHON_MODULE=ON \
        -DBUILD_GUI=ON \
        -DBUNDLE_OPEN3D_ML=ON \
        -DOPEN3D_ML_ROOT=../Open3D-ML \
        .. \
make -j$(nproc) 
make install 
make install-pip-package
```

Pytorch gets installed by wheels from [here](https://github.com/isl-org/open3d_downloads/releases/tag/torch1.7.1).
It does compile and the Open3D python package gets installed as well.
Unfortunately, when I import the module in an environment without GPU support, the following error occurs:

```
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/open3d/__init__.py", line 90, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'

```
Once the docker has access to the GPU it seems to work:

```
>>> import open3d as o3d
>>> o3d.core.cuda.is_available()
True
>>> import torch
>>> torch.cuda.is_available()
True
>>> import open3d.ml.torch as ml3d 
>>> 
```

My question is if it is possible to install Open3D in such a way that both CPU and GPU access is possible. Or am I doing something wrong within installation?

**To Reproduce**

docker run  <IMAGE-ID> python -c "import open3d;"

No error for:

docker run --gpus all <IMAGE-ID> python -c "import open3d;"

**Environment:**

- Operating system: (e.g. OSX 10.15, Ubuntu 18.04, Windows 10 64-bit)
- Python version: (e.g. Python 3.6)
- Open3D version:
- Is this remote workstation?: yes or no
- How did you install Open3D?: (e.g. pip, conda, build from source)
- Compiler version (if built from source): (e.g. gcc 7.5, clang 7.0)

**Additional context**

**Comment by maxim0815** [comment]
Sorry I forgot to give some information about the **Environment**:

- Operating system: nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04
- Python version: Python 3.8.10
- Open3D version: 0.14
- Is this remote workstation?: Docker
- How did you install Open3D?: build from source
- Compiler version (if built from source): GCC 9.3.0

**Comment by yxlao** [comment]
Essentially, you'll need to compile twice:

1. config with CUDA ON
2. build
3. config with CUDA OFF. 
4. build

The result is a Python wheel with both the CPU and CUDA object. This is how we build the pre-compiled Python package.

The easiest way to get such a wheel is to run the following command from the *host*:
```bash
cd .github/workflows
./docker_build.sh cuda_wheel_py38_dev # or whatever version you want
```

If you want more details, check out: 
- https://github.com/isl-org/Open3D/blob/master/.github/workflows/Dockerfile.wheel
- https://github.com/isl-org/Open3D/blob/ea252499eca8a36321abbcf01a095bbc28fa9eba/util/ci_utils.sh#L151

**Comment by orgicus** [comment]
@yxlao I have tried your advice above (build with `BUILD_CUDA_MODULE` to `ON`, don't delete build folder, set `BUILD_CUDA_MODULE` to `OFF`), however I ran into linking errors:

```
32>   Creating library C:/Users/george.profenza/Documents/gp/ZED-OSC/code/Open3D/build/lib/Release/Python/cpu/pybind.lib and object C:/Users/george.profenza/Documents/gp/ZED-OSC/code/Open3D/build/lib/Release/Python/cpu/pybind.exp
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::PointCloudTouchCUDA(class std::shared_ptr<class open3d::core::HashMap> &,class open3d::core::Tensor const &,class open3d::core::Tensor &,int,float,float)" (?PointCloudTouchCUDA@voxel_grid@kernel@geometry@t@open3d@@YAXAEAV?$shared_ptr@VHashMap@core@open3d@@@std@@AEBVTensor@core@5@AEAV895@HMM@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::DepthTouchCUDA(class std::shared_ptr<class open3d::core::HashMap> &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor &,int,float,float,float,float,int)" (?DepthTouchCUDA@voxel_grid@kernel@geometry@t@open3d@@YAXAEAV?$shared_ptr@VHashMap@core@open3d@@@std@@AEBVTensor@core@5@11AEAV895@HMMMMH@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::GetVoxelCoordinatesAndFlattenedIndicesCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor &,class open3d::core::Tensor &,int,float)" (?GetVoxelCoordinatesAndFlattenedIndicesCUDA@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@0AEAV675@1HM@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::EstimateRangeCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,int,int,__int64,float,float,float,class open3d::core::Tensor &)" (?EstimateRangeCUDA@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@00HHH_JMMM1@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::IntegrateCUDA<float,float,float,float,float>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,float,float,float,float)" (??$IntegrateCUDA@MMMMM@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@000AEAVTensorMap@234@000HMMMM@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::IntegrateCUDA<float,float,float,unsigned short,unsigned short>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,float,float,float,float)" (??$IntegrateCUDA@MMMGG@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@000AEAVTensorMap@234@000HMMMM@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::IntegrateCUDA<unsigned short,unsigned char,float,float,float>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,float,float,float,float)" (??$IntegrateCUDA@GEMMM@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@000AEAVTensorMap@234@000HMMMM@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::IntegrateCUDA<unsigned short,unsigned char,float,unsigned short,unsigned short>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,float,float,float,float)" (??$IntegrateCUDA@GEMGG@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@000AEAVTensorMap@234@000HMMMM@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::RayCastCUDA<float,float,float>(class std::shared_ptr<class open3d::core::HashMap> &,class open3d::t::geometry::TensorMap const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,int,int,float,float,float,float,float,float,int)" (??$RayCastCUDA@MMM@voxel_grid@kernel@geometry@t@open3d@@YAXAEAV?$shared_ptr@VHashMap@core@open3d@@@std@@AEBVTensorMap@234@AEBVTensor@core@4@AEAV7234@22HHHMMMMMMH@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::RayCastCUDA<float,unsigned short,unsigned short>(class std::shared_ptr<class open3d::core::HashMap> &,class open3d::t::geometry::TensorMap const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,int,int,int,float,float,float,float,float,float,int)" (??$RayCastCUDA@MGG@voxel_grid@kernel@geometry@t@open3d@@YAXAEAV?$shared_ptr@VHashMap@core@open3d@@@std@@AEBVTensorMap@234@AEBVTensor@core@4@AEAV7234@22HHHMMMMMMH@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::ExtractPointCloudCUDA<float,float,float>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap const &,class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &,int,float,float,int &)" (??$ExtractPointCloudCUDA@MMM@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@000AEBVTensorMap@234@AEAV564@22HMMAEAH@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::ExtractPointCloudCUDA<float,unsigned short,unsigned short>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap const &,class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &,int,float,float,int &)" (??$ExtractPointCloudCUDA@MGG@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@000AEBVTensorMap@234@AEAV564@22HMMAEAH@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCUDA<float,float,float>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap const &,class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &,int,float,float,int &)" (??$ExtractTriangleMeshCUDA@MMM@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@0000AEBVTensorMap@234@AEAV564@222HMMAEAH@Z)
32>Open3D.lib(VoxelBlockGrid.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::voxel_grid::ExtractTriangleMeshCUDA<float,unsigned short,unsigned short>(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::t::geometry::TensorMap const &,class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &,class open3d::core::Tensor &,int,float,float,int &)" (??$ExtractTriangleMeshCUDA@MGG@voxel_grid@kernel@geometry@t@open3d@@YAXAEBVTensor@core@4@0000AEBVTensorMap@234@AEAV564@222HMMAEAH@Z)
32>Open3D.lib(Image.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::image::ToCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,double,double)" (?ToCUDA@image@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@NN@Z)
32>Open3D.lib(Image.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::image::ClipTransformCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,float,float,float,float)" (?ClipTransformCUDA@image@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@MMMM@Z)
32>Open3D.lib(Image.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::image::PyrDownDepthCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,float,float)" (?PyrDownDepthCUDA@image@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@MM@Z)
32>Open3D.lib(Image.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::image::CreateVertexMapCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,class open3d::core::Tensor const &,float)" (?CreateVertexMapCUDA@image@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@0M@Z)
32>Open3D.lib(Image.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::image::CreateNormalMapCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,float)" (?CreateNormalMapCUDA@image@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@M@Z)
32>Open3D.lib(Image.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::image::ColorizeDepthCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,float,float,float)" (?ColorizeDepthCUDA@image@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@MMM@Z)
32>Open3D.lib(Transform.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::transform::TransformPointsCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &)" (?TransformPointsCUDA@transform@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@@Z)
32>Open3D.lib(Transform.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::transform::TransformNormalsCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &)" (?TransformNormalsCUDA@transform@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@@Z)
32>Open3D.lib(Transform.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::transform::RotatePointsCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &,class open3d::core::Tensor const &)" (?RotatePointsCUDA@transform@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@0@Z)
32>Open3D.lib(Transform.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::transform::RotateNormalsCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor &)" (?RotateNormalsCUDA@transform@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@AEAV675@@Z)
32>Open3D.lib(PointCloud.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::pointcloud::UnprojectCUDA(class open3d::core::Tensor const &,class open3d::utility::optional<class std::reference_wrapper<class open3d::core::Tensor const > >,class open3d::core::Tensor &,class open3d::utility::optional<class std::reference_wrapper<class open3d::core::Tensor> >,class open3d::core::Tensor const &,class open3d::core::Tensor const &,float,float,__int64)" (?UnprojectCUDA@pointcloud@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@V?$optional@V?$reference_wrapper@$$CBVTensor@core@open3d@@@std@@@utility@5@AEAV675@V?$optional@V?$reference_wrapper@VTensor@core@open3d@@@std@@@95@00MM_J@Z)
32>Open3D.lib(PointCloud.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::pointcloud::ProjectCUDA(class open3d::core::Tensor &,class open3d::utility::optional<class std::reference_wrapper<class open3d::core::Tensor> >,class open3d::core::Tensor const &,class open3d::utility::optional<class std::reference_wrapper<class open3d::core::Tensor const > >,class open3d::core::Tensor const &,class open3d::core::Tensor const &,float,float)" (?ProjectCUDA@pointcloud@kernel@geometry@t@open3d@@YAXAEAVTensor@core@5@V?$optional@V?$reference_wrapper@VTensor@core@open3d@@@std@@@utility@5@AEBV675@V?$optional@V?$reference_wrapper@$$CBVTensor@core@open3d@@@std@@@95@22MM@Z)
32>Open3D.lib(PointCloud.obj) : error LNK2001: unresolved external symbol "void __cdecl open3d::t::geometry::kernel::pointcloud::GetPointMaskWithinAABBCUDA(class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor const &,class open3d::core::Tensor &)" (?GetPointMaskWithinAABBCUDA@pointcloud@kernel@geometry@t@open3d@@YAXAEBVTensor@core@5@00AEAV675@@Z)
32>C:\Users\george.profenza\Documents\gp\ZED-OSC\code\Open3D\build\lib\Release\Python\cpu\pybind.cp37-win_amd64.pyd : fatal error LNK1120: 27 unresolved externals
```

I don't understand why it's still trying to link against CUDA functions if the VS project was regenerated.
(What's interesting is that on in the current virtual environment I can import open3d just fine and run older scripts where I don't explicitly use cuda implementations of open3d structures. However, if I copy the cuda compiled .whl on another machine, install and import, I get the same error. This is on Windows 11 + CUDA 11.7 + VS2022 (with 2019 compiler))

Any tips on what cmake settings I could double check to get cpu pybind to compile ?

Thank you so much,
George
