### ISSUE TITLE
TypeError when creating PointCloud with realsense L515

### ISSUE THREAD

**Issue by optimono** [isl-org/Open3D#4424]
**Describe the bug**
Trying to create PointCloud using realsense sensor L515.
Got TypeError as follows:
```
[Open3D INFO] Capture started with RealSense camera f1150666
Traceback (most recent call last):
  File "/Users/w/open3d_test/main.py", line 64, in <module>
    transfer_2_pcd(config_filename)
  File "/Users/w/open3d_test/main.py", line 29, in transfer_2_pcd
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)
TypeError: create_from_rgbd_image(): incompatible function arguments. The following argument types are supported:
    1. (image: open3d::geometry::RGBDImage, intrinsic: open3d.cpu.pybind.camera.PinholeCameraIntrinsic, extrinsic: numpy.ndarray[numpy.float64[4, 4]] = array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), project_valid_depth_only: bool = True) -> open3d.cpu.pybind.geometry.PointCloud

Invoked with: RGBD Image pair [Aligned]
Color [size=(640,480), channels=3, format=UInt8, device=CPU:0]
Depth [size=(640,480), channels=1, format=UInt16, device=CPU:0], PinholeCameraIntrinsic with width = 640 and height = 480.
Access intrinsics with intrinsic_matrix.
[Open3D INFO] Capture stopped.

Process finished with exit code 1
```

**To Reproduce**
The following is the python code used:
```
def transfer_2_pcd(config_filename):
    intrinsic = o3d.camera.PinholeCameraIntrinsic(o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)

    with open(config_filename) as cf:
        rs_cfg = o3d.t.io.RealSenseSensorConfig(json.load(cf))

    rs = o3d.t.io.RealSenseSensor()
    rs.init_sensor(rs_cfg, 0)
    rs.start_capture(True)  # true: start recording with capture
    for fid in range(150):
        im_rgbd = rs.capture_frame(True, True)  # wait for frames and align them
        # process im_rgbd.depth and im_rgbd.color
        pcd = o3d.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)

    rs.stop_capture()
```

Corresponding json used:
```
{
    "serial": "",
    "color_format": "RS2_FORMAT_RGB8",
    "color_resolution": "640,480",
    "depth_format": "RS2_FORMAT_Z16",
    "depth_resolution": "640,480",
    "fps": "30",
    "visual_preset": "RS2_L500_VISUAL_PRESET_MAX_RANGE"
 }
```

**Environment :**

- Operating system: OSX 11.6. Also tried on Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.14.1
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Additional context**
Moreover, I tried to save color&depth picture from bag file. Python code:
```
def read(bag_filename):
    bag_reader = o3d.t.io.RSBagReader()
    bag_reader.open(bag_filename)
    im_rgbd = bag_reader.next_frame()
    while not bag_reader.is_eof():
        # process im_rgbd.depth and im_rgbd.color
        im_rgbd = bag_reader.next_frame()

        o3d.io.write_image("color.jpg", im_rgbd.color)
        o3d.io.write_image("depth.png", im_rgbd.depth)

    bag_reader.close()
```
TypeError as follows:
```
[Open3D INFO] File bag_test.bag opened
Traceback (most recent call last):
  File "/Users/w/open3d_test/main.py", line 66, in <module>
    read(bag_filename)
  File "/Users/w/open3d_test/main.py", line 42, in read
    o3d.io.write_image("color.jpg", im_rgbd.color)
TypeError: write_image(): incompatible function arguments. The following argument types are supported:
    1. (filename: str, image: open3d.cpu.pybind.geometry.Image, quality: int = -1) -> bool

Invoked with: 'color.jpg', Image[size={480,640}, channels=3, UInt8, CPU:0]
```

**Comment by ssheorey** [comment]
Hi @optimono we are migrating to a new API with GPU acceleration. The functionality for the new API is in the `t` namespace, e.g. the `o3d.t.io.RealSenseSensor()` class that you have used. You cannot mix the new API with the old API directly. Please use `pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)` instead. To convert between the APIs, we provide `to_legacy()` and `from_legacy()` functions if needed.

**Comment by optimono** [comment]
hi @ssheorey , thanks for your reply. I tried `o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)`, but still got the following error:
```
[Open3D INFO] Capture started with RealSense camera f1150252
Traceback (most recent call last):
  File "/Users/w/open3d_test/main.py", line 68, in <module>
    transfer_2_pcd(config_filename)
  File "/Users/w/open3d_test/main.py", line 30, in transfer_2_pcd
    pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)
TypeError: create_from_rgbd_image(): incompatible function arguments. The following argument types are supported:
    1. (rgbd_image: open3d::t::geometry::RGBDImage, intrinsics: open3d.cpu.pybind.core.Tensor, extrinsics: open3d.cpu.pybind.core.Tensor = [[1.0 0.0 0.0 0.0],
 [0.0 1.0 0.0 0.0],
 [0.0 0.0 1.0 0.0],
 [0.0 0.0 0.0 1.0]]
Tensor[shape={4, 4}, stride={4, 1}, Float32, CPU:0, 0x7fd13d5a2460], depth_scale: float = 1000.0, depth_max: float = 3.0, stride: int = 1, with_normals: bool = False) -> open3d.cpu.pybind.t.geometry.PointCloud

Invoked with: RGBD Image pair [Aligned]
Color [size=(640,480), channels=3, format=UInt8, device=CPU:0]
Depth [size=(640,480), channels=1, format=UInt16, device=CPU:0], PinholeCameraIntrinsic with width = 640 and height = 480.
Access intrinsics with intrinsic_matrix.
[Open3D INFO] Capture stopped.

Process finished with exit code 1
```

Here is the function code I used:
```
def transfer_2_pcd(config_filename):
    intrinsic = o3d.camera.PinholeCameraIntrinsic(o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)

    with open(config_filename) as cf:
        rs_cfg = o3d.t.io.RealSenseSensorConfig(json.load(cf))

    rs = o3d.t.io.RealSenseSensor()
    rs.init_sensor(rs_cfg, 0)
    rs.start_capture(True)  # true: start recording with capture
    for fid in range(150):
        im_rgbd = rs.capture_frame(True, True)  # wait for frames and align them
        # process im_rgbd.depth and im_rgbd.color
        # pcd = o3d.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)
        pcd = o3d.t.geometry.PointCloud.create_from_rgbd_image(im_rgbd, intrinsic)

    rs.stop_capture()
```

**Comment by ssheorey** [comment]
Hi @optimono could you convert the `intrinsic` to the new Tensor data type?

For example, see: 

https://github.com/isl-org/Open3D/blob/61212b6c9a80fbb9cdde74a1991b50a98bb52c0b/examples/python/gui/online-processing.py#L106-L115

followed later by:

https://github.com/isl-org/Open3D/blob/61212b6c9a80fbb9cdde74a1991b50a98bb52c0b/examples/python/gui/online-processing.py#L164-L167
