### ISSUE TITLE
Reconstruction system error

### ISSUE THREAD

**Issue by azubu23202869** [isl-org/Open3D#4472]
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "D:\xx\RSTo\Open3D-0.14.1\examples\python\reconstruction_system\make_fragments.py", line 189, in process_single_fragment
    intrinsic, config)
  File "D:\xx\RSTo\Open3D-0.14.1\examples\python\reconstruction_system\make_fragments.py", line 163, in make_pointcloud_for_fragment
    intrinsic, config)
  File "D:\xx\RSTo\Open3D-0.14.1\examples\python\reconstruction_system\make_fragments.py", line 151, in integrate_rgb_frames_for_fragment
    volume.integrate(rgbd, intrinsic, np.linalg.inv(pose))
RuntimeError: [Open3D Error] (void __cdecl open3d::pipelines::integration::ScalableTSDFVolume::Integrate(const class open3d::geometry::RGBDImage &,const class open3d::camera::PinholeCameraIntrinsic &,const class Eigen::Matrix<double,4,4,0,4,4> &)) D:\a\Open3D\Open3D\cpp\open3d\pipelines\integration\ScalableTSDFVolume.cpp:78: [ScalableTSDFVolume::Integrate] depth image size is (640 x 480), but got (-1 x -1) from intrinsic.

"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_system.py", line 113, in <module>
    make_fragments.run(config)
  File "D:\xx\RSTo\Open3D-0.14.1\examples\python\reconstruction_system\make_fragments.py", line 209, in run
    for fragment_id in range(n_fragments))
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\parallel.py", line 1061, in __call__
    self.retrieve()
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\azubu\anaconda3\envs\myenv\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: [Open3D Error] (void __cdecl open3d::pipelines::integration::ScalableTSDFVolume::Integrate(const class open3d::geometry::RGBDImage &,const class open3d::camera::PinholeCameraIntrinsic &,const class Eigen::Matrix<double,4,4,0,4,4> &)) D:\a\Open3D\Open3D\cpp\open3d\pipelines\integration\ScalableTSDFVolume.cpp:78: [ScalableTSDFVolume::Integrate] depth image size is (640 x 480), but got (-1 x -1) from intrinsic.
```
- Operating system: Windows 10 64-bit
- Python version: Python 3.7
- Open3D version:0.14.1
- Is this remote workstation?: no
- How did you install Open3D?: pip

run  python realsense_recorder.py --record_rosbag to get bag
run python run_system.py config/realsense.json --make --register --refine --integrate  to reconstruction

**Comment by theNded** [comment]
Apparently you did not change the `optional/read_from_bag_file.json` to your customized path in `realsense.json`.
