### ISSUE TITLE
Command line interface fails on Windows (missing `nis` package)

### ISSUE THREAD

**Issue by joseph-sch** [isl-org/Open3D#4884]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

When running the `open3d` command on Windows, the execution **stops** due to a missing import with `ModuleNotFoundError: No module named 'nis'`.

### Steps to reproduce the bug

```python
Run `open3d` or `open3d example --list` in a console on Windows.
```

### Error message

```
Traceback (most recent call last):
  File "C:\Users\Joseph\miniconda3\envs\open3d_0_15\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Joseph\miniconda3\envs\open3d_0_15\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Joseph\miniconda3\envs\open3d_0_15\Scripts\open3d.exe\__main__.py", line 4, in <module>
  File "C:\Users\Joseph\miniconda3\envs\open3d_0_15\lib\site-packages\open3d\tools\cli.py", line 28, in <module>
    from nis import cat
ModuleNotFoundError: No module named 'nis'
```

### Expected behavior

The command line should work on Windows.

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.9
- Open3D version: 0.15.1
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

The issue is at https://github.com/isl-org/Open3D/blob/ebc8f8c60d0a0571904cdefb60e61b15403e7022/python/tools/cli.py#L28

**I do not think that the import is used at all. Removing the line or commenting it out solves the issue.**

(The nis library is a standard library available on Unix systems only, as per [the Python 3 documentation of the `nis` module](https://docs.python.org/3/library/nis.html).

**Comment by yxlao** [comment]
Thanks. You are right, this line should be removed. I don't know why it was there.
