### ISSUE TITLE
How to use cuda in dense RGB-D SLAM on win10

### ISSUE THREAD

**Issue by lvkoala** [isl-org/Open3D#5256]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi,

I am trying to run the python dense SLAM example. I worked in using CPU but when I tried to run it using CUDA, such error occur

```
Traceback (most recent call last):
  File "D:\PyProjects\pyOpen3D\open3d\python\t_reconstruction_system\dense_slam.py", line 121, in <module>
    volume, poses = slam(depth_file_names, color_file_names, intrinsic,
  File "D:\PyProjects\pyOpen3D\open3d\python\t_reconstruction_system\dense_slam.py", line 46, in slam
    model = o3d.t.pipelines.slam.Model(config.voxel_size, 16,
RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::core::DeviceHashBackend> __cdecl open3d::core::CreateDeviceHashBackend(__int64,const class open3d::core::Dtype &,const class open3d::cor
e::SizeVector &,const class std::vector<class open3d::core::Dtype,class std::allocator<class open3d::core::Dtype> > &,const class std::vector<class open3d::core::SizeVector,class std::allocator<class op
en3d::core::SizeVector> > &,const class open3d::core::Device &,const enum open3d::core::HashBackendType &)) D:\a\Open3D\Open3D\cpp\open3d\core\hashmap\DeviceHashBackend.cpp:57: [CreateDeviceHashBackend]
: Unimplemented device
```

In addition I tried `python -c 'import open3d as o3d; print(o3d.core.cuda.is_available())'` and it returned `False`

Versions currently installed:
- Distribution: Windows 10
- Open3D 0.15.1
- CUDA 11.7

I had read the issue and document. I am a bit confused about whether open3d support cuda on windows. Could you please tell me how to do that?

Thanks

**Comment by yxlao** [comment]
Currently, the released Open3D Windows wheel is not CUDA-enabled. We may enable CPU+CUDA for Windows by default in future releases.  The Ubuntu wheel is CUDA-enabled with CUDA 11.x by default, so you may use Ubuntu as well. 

Here, we provide experimental wheels for Python 3.7, 3.8, 3.9 on Windows witgh CUDA 11.x. 

## Usage

```powershell
conda activate your-env-name
pip install xxx.whl
python -c 'import open3d as o3d; print(o3d.core.cuda.is_available())
```

**Supported Python versions:**

- Python 3.6: not supported. 
- Python 3.7: supported ([link](https://github.com/isl-org/open3d_downloads/releases/download/v0.15.2-windows-cuda/open3d-0.15.2-cp37-cp37m-win_amd64.whl)).
- Python 3.8: supported ([link](https://github.com/isl-org/open3d_downloads/releases/download/v0.15.2-windows-cuda/open3d-0.15.2-cp38-cp38-win_amd64.whl)).
- Python 3.9: supported ([link](https://github.com/isl-org/open3d_downloads/releases/download/v0.15.2-windows-cuda/open3d-0.15.2-cp39-cp39-win_amd64.whl)).
- Python 3.10: not supported. 

**Supported devices:**

- CPU Tensor API: **No**. To use the CPU Tensor API, you can use the official pip package for CPU support.
- CUDA Tensor API: Yes.
- Legacy CPU code: Yes.



## Compile from source

Alternatively, you can compile from source with CUDA enabled. First, get this patch: https://github.com/isl-org/Open3D/pull/5259, and then compile and install with:

```powershell
conda activate your-env-name

cd Open3D
mkdir build
cd build
cmake **-DBUILD_CUDA_MODULE=ON** -DDEVELOPER_BUILD=OFF ..
cmake --build . --config Release --parallel $env:NUMBER_OF_PROCESSORS --target install-pip-package

python -c 'import open3d as o3d; print(o3d.core.cuda.is_available())
```
