### ISSUE TITLE
dense_slam_gui error with own dataset

### ISSUE THREAD

**Issue by Wulder** [isl-org/Open3D#5279]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I try start dense_slam_gui.py with dataset from here: https://github.com/ylabo0717/iPhone-3D-Reconstruction (hotel room) and get error:

Exception in thread UpdateMain:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/USERNAME/PycharmProjects/Escan/t_reconstruction_system/dense_slam_gui.py", line 384, in update_main
    result = self.model.track_frame_to_model(
RuntimeError: [Open3D Error] (void open3d::t::pipelines::kernel::DecodeAndSolve6x6(const open3d::core::Tensor&, open3d::core::Tensor&, float&, int&)) /home/tUSERNAME/Open3D/cpp/open3d/t/pipelines/kernel/TransformationConverter.cpp:145: Singular 6x6 linear system detected, tracking failed.

What does this mean and how to solve it?

**Comment by Gratao** [comment]
I am also having the same error.

**Comment by HJGrant** [comment]
I have the same error with my dataset, has anyone found a fix ?
