### ISSUE TITLE
Which one is the example for real-time 3D reconstruction example like youtube?

### ISSUE THREAD

**Issue by youb1649** [isl-org/Open3D#5379]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

I found a real-time 3D reconstruction example in one video on youtube like [https://youtu.be/pLCVCH7ypI4](url).
If I can create an indoor environment as a mesh, especially with real-time 3D reconstruction techniques, that is exactly the solution that I want to have. It would be appreciated if someone could introduce the process of configuring this with open3d.

Also, dense_slam_gui.py makes ab error like below in my computer.

Config file was not provided, falling back to default dataset.
Traceback (most recent call last):
  File "c:\Open3D\examples\python\t_reconstruction_system\dense_slam_gui.py", line 476, in <module>
    config = get_default_dataset(config)
  File "c:\Open3D\examples\python\t_reconstruction_system\common.py", line 99, in get_default_dataset
    config = lounge_dataloader(config)
  File "c:\Open3D\examples\python\t_reconstruction_system\common.py", line 65, in lounge_dataloader
    lounge_rgbd = o3d.data.LoungeRGBDImages()
AttributeError: module 'open3d.cpu.pybind.data' has no attribute 'LoungeRGBDImages'

It would be appreciated as well if someone explain the reason for the error and the solution how it works.

Thanks!

**Comment by yuecideng** [comment]
Hi, could you provide more infomation about the Open3D, Python and System information? Please see the issue [temple](https://github.com/isl-org/Open3D/issues/new?assignees=&labels=bug&template=1-bug-report.yml&title=Summarize+the+bug+%28e.g.%2C+%22Segmentation+Fault+for+Colored+Point+Cloud+Registration%22%29).

**Comment by youb1649** [comment]
OS: window 11
Python: 3.9.13
Open3D: 0.15.1

Exactly I want to play this on my computer.

![image](https://user-images.githubusercontent.com/45025407/181877992-2e9ca693-3b4b-4f2e-b462-fe0bd8a89bd1.png)

**Comment by youb1649** [comment]
I met one new error message.

class utils::PostconditionPanic
in enum filament::RenderableManager::Builder::Result __cdecl filament::RenderableManager::Builder::build(class filament::Engine &,class utils::Entity):235
in file D:\a\filament\filament\filament\src\components\RenderableManager.cpp
reason: [entity=50] AABB can't be empty, unless culling is disabled and the object is not a shadow caster/receiver

![image](https://user-images.githubusercontent.com/45025407/183006954-dba4eae9-4206-45ed-b2f0-10fd18c7f1dc.png)

Does anyone know about the error and how to solve it?

**Comment by FraDePace** [comment]
were you able to solve it? I am facing the same error

**Comment by EwingKang** [comment]
I'm not sure about  the example. But if the data contains NaN, Open3D will trigger this error.
