### ISSUE TITLE
Dataset downloading fails in LoungeRGBDImages function.

### ISSUE THREAD

**Issue by youb1649** [isl-org/Open3D#5385]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

'LoungeRGBDImages' function doesn't work with this message
  File "c:\Open3D\examples\python\t_reconstruction_system\TestLoungeRGBDImages.py", line 2, in <module>
    dataset = o3d.data.LoungeRGBDImages()
AttributeError: module 'open3d.cpu.pybind.data' has no attribute 'LoungeRGBDImages'

### Steps to reproduce the bug

```python
# full source code
import open3d as o3d
dataset = o3d.data.LoungeRGBDImages()

rgbd_images = []
for i in range(len(dataset.depth_paths)):
    color_raw = o3d.io.read_image(dataset.color_paths[i])
    depth_raw = o3d.io.read_image(dataset.depth_paths[i])
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
                                               color_raw, depth_raw)
    rgbd_images.append(rgbd_image)

mesh = o3d.io.read_triangle_mesh(dataset.reconstruction_path)
```

### Error message

_reconstruction_system/TestLoungeRGBDImages.py
Traceback (most recent call last):
  File "c:\Open3D\examples\python\t_reconstruction_system\TestLoungeRGBDImages.py", line 2, in <module>
    dataset = o3d.data.LoungeRGBDImages()
AttributeError: module 'open3d.cpu.pybind.data' has no attribute 'LoungeRGBDImages'

### Expected behavior

1. download linked dataset
2. work well

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit
- Python version: 3.9.13
- Open3D version: 0.15.1
- System architecture: arm64 
- Is this a remote workstation?: no
- How did you install Open3D?: pip
- Compiler version (if built from source): VS 19
- Country: South Korea (Possibly This may have caused problems because of the network.)
```

### Additional information

# full source code.
import open3d as o3d
dataset = o3d.data.LoungeRGBDImages()

rgbd_images = []
for i in range(len(dataset.depth_paths)):
    color_raw = o3d.io.read_image(dataset.color_paths[i])
    depth_raw = o3d.io.read_image(dataset.depth_paths[i])
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
                                               color_raw, depth_raw)
    rgbd_images.append(rgbd_image)

mesh = o3d.io.read_triangle_mesh(dataset.reconstruction_path)

**Comment by Bing-Xiong** [comment]
same here
