### ISSUE TITLE
Python Import Error built on Win10 RTX3090 CUDA 11.4

### ISSUE THREAD

**Issue by JasonDoingGreat** [isl-org/Open3D#5803]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Windows 10, with CUDA 11.4 of RTX3090 GPU, Anaconda Python3.9.12) with CMake-GUI:
```
Choose Visual Studio 16 2019, x64 platform
Configure
Check BUILD_CUDA_MODULE
Configure
Generate
Open Visual Studio 2019, Build ALL
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Codes\Open3D_build\lib\python_package\open3d\__init__.py", line 76, in <module>
    from open3d.cuda.pybind import (camera, data, geometry, io,
ImportError: RedwoodIndoorLivingRoom1: PyType_Ready failed (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 281: invalid continuation byte)!
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.9.12 / output from `import sys; print(sys.version)`
- Open3D version: 0.16.0 output from python: `print(open3d.__version__)`
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): MSVC 19.29.30142.1
```

**Comment by Buffyqsf** [comment]
have you solve this? I've met a similar error and don't know how to sovle it.

**Comment by ahaheng** [comment]
I avoid this problem by building from source code with version=0.15.1.

**Comment by Buffyqsf** [comment]
Thank you very much. I turn to Linux at last haha, but still thank you
