### ISSUE TITLE
Is it possible to store the output of draw_geometries() as a ply?

### ISSUE THREAD

**Issue by hariramrajgopal** [isl-org/Open3D#5846]
I need to store the ouput given by draw_geometries() as a ply. I tried another method but was getting a lot of errors.

    o3d.visualization.draw_geometries([segments[i] for i in range(max_plane_idx)]+[rest])
    final_p = [segments[i] for i in range(max_plane_idx)] + [rest]
    ply = o3d.geometry.PointCloud()
    ply.points = o3d.utility.Vector3dVector(final_p)
    o3d.io.write_point_cloud("C:/Users/gokug/Desktop/copy_of_fragment.ply", ply)
    print("File Saved")

The error I got was:

Traceback (most recent call last):
  File "C:\Users\gokug\OneDrive\Desktop\Addon_automatic_segmentation.blend\Text", line 110, in execute
  File "C:\Users\gokug\OneDrive\Desktop\Addon_automatic_segmentation.blend\Text", line 88, in main
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
Error: Python: Traceback (most recent call last):
  File "C:\Users\gokug\OneDrive\Desktop\Addon_automatic_segmentation.blend\Text", line 110, in execute
  File "C:\Users\gokug\OneDrive\Desktop\Addon_automatic_segmentation.blend\Text", line 88, in main
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

**Comment by kqdidit119** [comment]
Is this Organization participating in GSoC 2023? Will it be there for projects?
