### ISSUE TITLE
Summarize the question. (e.g., "How to run reconstruction system with RealSense D435i? ")

### ISSUE THREAD

**Issue by Karin-Sugi** [isl-org/Open3D#6087]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, I'm trying to use open3d in Ubuntu18.04 on virtualbox (on windows11). 
I installed open3d with pip and check it with `python3 -c "import open3d as o3d; print(o3d.__version__)"`, then I got the message saying `illegal instruction`. How can i fix it?

On my ubuntu, python is `version2.7`, so i used python3 which is `version3.6.9` instead.

Thanks in advance, 
Karin

**Comment by hradec** [comment]
I'm having the same issue. My CPU is and old Xeon, so maybe I need change some compiling flags and rebuild to build for my cpu? 

this is my lscpu output: 
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           44
Model name:                      Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         3569.871
CPU max MHz:                     3068.0000
CPU min MHz:                     1600.0000
BogoMIPS:                        7359.95
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX vulnerable
Vulnerability Mds:               Vulnerable; SMT vulnerable
Vulnerability Meltdown:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 
                                 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm epb ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d
```

**Comment by hradec** [comment]
btw, I don't think this is a question... it's more of a bug, since we can't run open3d at all.

**Comment by hradec** [comment]
Today I tried building with `-DCMAKE_BUILD_TYPE=Debug`, but not much luck either.
This is the gdb stack trace when running `Open3D`:
```
$ gdb ./Open3D/Open3D 
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Open3D/Open3D...r
done.
(gdb) r
Starting program: /RAID/atomo/home/rhradec/dev/open3d/build-debug/Open3D/Open3D 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x000055555594f30e in _GLOBAL__sub_I_bvh_collider.cpp ()
(gdb) bt
#0  0x000055555594f30e in _GLOBAL__sub_I_bvh_collider.cpp ()
#1  0x000055555cde27cd in __libc_csu_init ()
#2  0x00007ffff73310de in __libc_start_main () from /usr/lib/libc.so.6
#3  0x0000555555950eae in _start ()
(gdb) 
```

**Comment by hradec** [comment]
I opened a new bug and put the solution for this problem there: https://github.com/isl-org/Open3D/issues/6127
