### ISSUE TITLE
Using o3d.t.geometry.TriangleMesh.from_legacy in PyTorch Dataset Class Gives Segmentation Fault Error

### ISSUE THREAD

**Issue by tommycwh** [isl-org/Open3D#6220]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

I would like to process a TriangleMesh in my PyTorch Dataset class, so I create my mesh using ```o3d.t.geometry.TriangleMesh.from_legacy``` following the instructions in this [page](http://www.open3d.org/docs/latest/tutorial/geometry/ray_casting.html)

```
mesh_o3d = o3d.io.read_triangle_mesh(path) 
print("Mesh loaded.")
mesh_o3d = o3d.t.geometry.TriangleMesh.from_legacy(mesh_o3d)
print("Mesh created from legacy.")
```
My PyTorch Dataset class, inlcuding these two lines, runs without any problem, but only when I set ```num_workers=0```, i.e., multiprocessing is not enabled for the Dataset class.

### Steps to reproduce the bug

```python
However, if I set =1 (or any number >1), the message ```"Mesh created from legacy."``` is not printed out, and it seems that the line ```mesh_o3d = o3d.t.geometry.TriangleMesh.from_legacy(mesh_o3d)``` is giving a segmentation error (see below).
```

### Error message

```
Mesh loaded.                                                                                                                                                                                                    
ERROR: Unexpected segmentation fault encountered in worker.                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                              
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data                                                                                 
    data = self._data_queue.get(timeout=timeout)                                                                                                                                                                
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/queues.py", line 113, in get                                                                                                               
    if not self._poll(timeout):
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 221529) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/diffusion/main.py", line 21, in <module>
    cli_main()
  File "/workspace/diffusion/main.py", line 10, in cli_main
    cli = LightningCLI(L.LightningModule, L.LightningDataModule, 
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 353, in __init__
    self._run_subcommand(self.subcommand)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/cli.py", line 642, in _run_subcommand
    fn(**fn_kwargs)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1018, in _run_stage
    self.fit_loop.run()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 189, in advance
    batch = next(data_fetcher)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 136, in __next__
    self._fetch_next_batch(self.dataloader_iter)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 150, in _fetch_next_batch
    batch = next(iterator)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 284, in __next__
    out = next(self._iterator)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 65, in __next__
    out[i] = next(self.iterators[i])
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 221529) exited unexpectedly
```

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04
- Python version: Python 3.10
- Open3D version: 0.17.0+ff22900c9
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: pip or build from source (both inside a conda env)
- Compiler version (if built from source): gcc 9.4.0
```

### Additional information

Versions of related packages:
- pytorch-lightning        2.0.3
- torch                    1.13.1+cu116 or 2.0.0
- torchvision              0.14.1+cu116

**Comment by chexenia** [comment]
The same behavior for open3d version 0.16

**Comment by dreamcubeblock** [comment]
same problem when i compute point cloud normals

**Comment by dreamcubeblock** [comment]
Have you got any solution?

**Comment by yuecideng** [comment]
Just for reference: http://www.open3d.org/docs/release/compilation.html#ml-module
check the CXX ABI by:
```python
python -c "import torch; print(torch._C._GLIBCXX_USE_CXX11_ABI)"
python -c "import open3d; print(open3d.pybind._GLIBCXX_USE_CXX11_ABI)"
```

**Comment by tommycwh** [comment]
> Just for reference: http://www.open3d.org/docs/release/compilation.html#ml-module check the CXX ABI by:
> 
> ```python
> python -c "import torch; print(torch._C._GLIBCXX_USE_CXX11_ABI)"
> python -c "import open3d; print(open3d.pybind._GLIBCXX_USE_CXX11_ABI)"
> ```

Both of these lines return False in my environment.

I tried to build Open3D with Open3D-ML from source as suggested in the documentation (http://www.open3d.org/docs/release/compilation.html#ml-module), but the problem persists. 

This is the cmake command I used:
```

cmake \
-DPython3_ROOT=<my_path_to_python> \
-DWITH_OPENMP=ON \
-DBUILD_CUDA_MODULE=ON \
-DGLIBCXX_USE_CXX11_ABI=OFF \
-DBUILD_PYTORCH_OPS=ON \
-DBUNDLE_OPEN3D_ML=ON \
-DOPEN3D_ML_ROOT=<my_path_to_Open3D-ML_repo> \
..
```

**Comment by ssheorey** [comment]
Hi @tommycwh @chexenia  @dreamcubeblock please set `multiprocessing.set_start_method('forkserver')` at the start of your program and check if this solves the problem. See Python multiprocessing documentation for how to correctly use multithreaded code (Open3D is heavily multithreaded) with Python multiprocessing.

**Comment by tommycwh** [comment]
> Hi @tommycwh @chexenia @dreamcubeblock please set `multiprocessing.set_start_method('forkserver')` at the start of your program and check if this solves the problem. See Python multiprocessing documentation for how to correctly use multithreaded code (Open3D is heavily multithreaded) with Python multiprocessing.

It does not work even after setting `multiprocessing.set_start_method('forkserver')`. In fact, from the error message it seems to tell that 'forkserver' is already set.

Below are the error messages and the code I used for testing.

Error messages:
```
Traceback (most recent call last):                                                                                                                                                                              
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/forkserver.py", line 274, in main                                                                                                          
    code = _serve_one(child_r, fds,                                                                                                                                                                             
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one                                                                                                    
    code = spawn._main(child_r, parent_sentinel)                                                                                                                                                                
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/spawn.py", line 125, in _main                                                                                                              
    prepare(preparation_data)                                                                                                                                                                                   
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare                                                                                                            
    _fixup_main_from_path(data['init_main_from_path'])                                                                                                                                                          
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path                                                                                              
    main_content = runpy.run_path(main_path,                                                                                                                                                                    
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/runpy.py", line 289, in run_path                                                                                                                           
    return _run_module_code(code, init_globals, run_name,                                                                                                                                                       
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/runpy.py", line 96, in _run_module_code                                                                                                                    
    _run_code(code, mod_globals, init_globals,                                                                                                                                                                  
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/runpy.py", line 86, in _run_code                                                                                                                           
    exec(code, run_globals)                                                                                                                                                                                     
  File "#####.py", line 3, in <module>                                                                                                                    
    multiprocessing.set_start_method('forkserver')                                                                                                                                                              
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
Traceback (most recent call last):
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "#####.py", line 74, in <module>
    for data in loader :
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1294, in _get_data
    success, data = self._try_get_data()
  File "/root/anaconda3/envs/diff_dev/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 77277) exited unexpectedly

```

Testing code:
```
# To test
import multiprocessing
multiprocessing.set_start_method('forkserver')

# imports
import numpy as np
import trimesh
from torch.utils.data import Dataset, DataLoader
import open3d as o3d

class SDFDataset(Dataset):
    def __init__(
        self, 
        mesh_path: str = "mesh.obj",
        N: int = 10,
        N_query: int = 100,
    ):
        self.mesh_path = mesh_path
        self.N = N
        self.N_query = N_query
        
    def __len__(self) :
        return self.N
    
    def __getitem__(self, index) :
        # Load mesh
        mesh_trimesh = trimesh.load(self.mesh_path)
        vs = np.array(mesh_trimesh.vertices) # (V,3)
        fs = np.array(mesh_trimesh.faces) # (F,3)
        print("vs: ", vs.shape, vs.dtype)
        print("fs: ", fs.shape, fs.dtype)
        
        # Prepare o3d mesh (for computing distance from mesh)
        vs = o3d.utility.Vector3dVector(vs)
        fs = o3d.utility.Vector3iVector(fs)
        mesh_o3d = o3d.geometry.TriangleMesh(vs, fs)
        mesh_o3d = o3d.t.geometry.TriangleMesh.from_legacy(mesh_o3d)
        print("mesh_o3d: ", mesh_o3d)
        
        # Generate random query points
        query_points = np.random.normal(0,1,(self.N_query,3))
        query_points = o3d.core.Tensor(query_points, dtype=o3d.core.Dtype.Float32)
        
        # Create a scene and add the triangle mesh
        scene = o3d.t.geometry.RaycastingScene()
        _ = scene.add_triangles(mesh_o3d)  # we do not need the geometry ID for mesh
        
        
        # Compute distance of the query point from the surface
        signed_distance = scene.compute_signed_distance(query_points) # shape: (N)
        signed_distance = signed_distance.numpy()
        print("signed_distance: ", signed_distance.shape, signed_distance.dtype)
        
        return signed_distance
        
if __name__ == "__main__" :
    # Create dataset and dataloader objects
    ds_kwargs = dict(
        mesh_path='../../data/cow_mesh/cow.obj',
        N=3, # dataset size
        N_query=100, # number of query pts to compute signed distances
    )
    ds = SDFDataset(**ds_kwargs)

    loader_kwargs = dict(
        batch_size=1,
#         num_workers=0, # disable multiprocessing
        num_workers=1, # enable multiprocessing
        shuffle=False,
    )
    loader = DataLoader(ds, **loader_kwargs)
    
    
    for data in loader :
        print("data: ", data.shape, data.min(), data.mean(), data.max())
```

With ```num_workers=0``` set for the dataloader, it runs fine with no error. However, with ```num_workers=1```, the error aforementioned is raised.

**Comment by tommycwh** [comment]
Hello @ssheorey, I just want to see if there is any progress about this issue. If there is anything that I should/can help test or any information I could provide, please let me know.

**Comment by tommycwh** [comment]
While this does not solve the original problem, in which the mesh can be different every time __getitem__(...) is executed, I found that the program runs without problem if:
(1) the RaycastingScene is created in Dataset.__init__(...); and
(2) query_points is of type np.ndarray with dtype=np.float32 instead of o3d.core.Tensor.

So, if the application is to query one single RaycastingScene (e.g., with the same mesh) but with different sets of query points in every iteration, the following works:

```
# imports
import numpy as np
import trimesh
from torch.utils.data import Dataset, DataLoader
import open3d as o3d

class SDFDataset(Dataset):
    def __init__(
        self, 
        mesh_path: str = "mesh.obj",
        N: int = 10,
        N_query: int = 100,
    ):
        self.mesh_path = mesh_path
        self.N = N
        self.N_query = N_query

        # Load mesh
        mesh_trimesh = trimesh.load(self.mesh_path)
        vs = np.array(mesh_trimesh.vertices) # (V,3)
        fs = np.array(mesh_trimesh.faces) # (F,3)
        print("vs: ", vs.shape, vs.dtype)
        print("fs: ", fs.shape, fs.dtype)
        
        # Prepare o3d mesh (for computing distance from mesh)
        vs = o3d.utility.Vector3dVector(vs)
        fs = o3d.utility.Vector3iVector(fs)
        mesh_o3d = o3d.geometry.TriangleMesh(vs, fs)
        mesh_o3d = o3d.t.geometry.TriangleMesh.from_legacy(mesh_o3d)
        print("mesh_o3d: ", mesh_o3d)

        # Create a scene and add the triangle mesh
        scene = o3d.t.geometry.RaycastingScene()
        _ = scene.add_triangles(mesh_o3d)  # we do not need the geometry ID for mesh

        self.scene = scene
        
    def __len__(self) :
        return self.N
    
    def __getitem__(self, index) :
        
        # Generate random query points
        query_points = np.random.normal(0,1,(self.N_query,3))
        # query_points = o3d.core.Tensor(query_points, dtype=o3d.core.Dtype.Float32) # does not work
        query_points = query_points.astype(np.float32)
        
        # Compute distance of the query point from the surface
        # signed_distance = scene.compute_signed_distance(query_points) # shape: (N)
        signed_distance = self.scene.compute_signed_distance(query_points) # shape: (N)
        signed_distance = signed_distance.numpy()
        print("signed_distance: ", signed_distance.shape, signed_distance.dtype)
        
        return signed_distance
        
if __name__ == "__main__" :
    # Create dataset and dataloader objects
    ds_kwargs = dict(
        mesh_path='data/cow_mesh/cow.obj',
        N=3, # dataset size
        N_query=100, # number of query pts to compute signed distances
    )
    ds = SDFDataset(**ds_kwargs)

    loader_kwargs = dict(
        batch_size=1,
#         num_workers=0, # disable multiprocessing
        num_workers=1, # enable multiprocessing
        shuffle=False,
    )
    loader = DataLoader(ds, **loader_kwargs)
    
    
    for data in loader :
        print("data: ", data.shape, data.min(), data.mean(), data.max())
```
