### ISSUE TITLE
Open3D0.17  causes ImportError: DLL load failed while importing pybind.

### ISSUE THREAD

**Issue by skye285** [isl-org/Open3D#6424]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I am building the latest master with CUDA=ON, but still keep running into DLL load failed while importing pybind.
 I get the same issue when I build this with cuda=Off

I had no errors building from source and created a .whl per instructions for python3.9 , on Windows11.

```
from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: DLL load failed while importing pybind: The specified module could not be found.
```

#### I built Open3D-0.17 (on Win 11, with CUDA12.2 ) following the docs:
```
mkdir build
cd build
Cmake-gui : configure and generate. **This uses the same python as system
cmake --build . --config Release --target ALL_BUILD


_:: Create pip package in build/lib_
:: This creates a .whl file that you can install manually.
cmake --build . --config Release --target pip-package



### Error message

Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sku\AppData\Local\Programs\Python\Python39\lib\site-packages\open3d\__init__.py", line 93, in <module>
    from open3d.cpu.pybind import (core, camera, data, geometry, io, pipelines,
ModuleNotFoundError: No module named 'open3d.cpu'


### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit
- Python version: Python 3.9 / 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]`
- Open3D version: 0.17 (latest from git pull)**`print(open3d.__version__)` fails as import fails.
- System architecture: x64-based PC/nvidia
- Is this a remote workstation?:  no
- How did you install Open3D?: build from source / followed by pip install *.whl
- Compiler version (if built from source): Visual studio 17 2022
```

### Additional information
- It seems I have [this similar issue](https://github.com/isl-org/Open3D/issues/5734) similar issue, but I get this even without CUDA,
- After seeing [this post ](https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python)on Win11 security controls, I have tried adding os.add_dll_directory ('%Users\python\dlls) in init.py, but to no avail.
- I downloaded procmon to verify dll loading, but even with the above statement, I don't see it loading the dlls. I suspect this is where the issue is but I have looked everywhere and haven't found a solution.

**Comment by skye285** [comment]
I had the same issue with building the 0.16 too (hence edited title), and tried the latest master instead but still get the same error.

**Comment by Neflux** [comment]
I'm getting the same problem on 0.18.0: `ModuleNotFoundError: No module named 'open3d.cpu'`.
Surprisingly, if I avoid doing that assessment in the Dockerfile, I start the container, activate open3d manually and do `import open3d` on python, it just works. With full CUDA support.

Here's how to reproduce:
```# Base image with CUDA and OpenGL support
FROM nvidia/cudagl:11.4.2-devel-ubuntu20.04

# Non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies and add Kitware repository in one step
RUN apt-get update && apt-get install -y \
    wget build-essential ca-certificates gpg git \
    xorg-dev libxcb-shm0 libglu1-mesa-dev python3-dev \
    clang-10 libc++-10-dev libc++abi-10-dev libsdl2-dev ninja-build \
    libxi-dev libtbb-dev libosmesa6-dev libudev-dev autoconf libtool \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update && apt-get install -y cmake \
    && rm -rf /var/lib/apt/lists/*

# PATH at this point: /opt/miniconda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Let's install ccache from source
RUN git clone https://github.com/ccache/ccache.git /ccache

WORKDIR /ccache
RUN git checkout v4.6.3 && mkdir build && cd build && \
    cmake .. \
    -DZSTD_FROM_INTERNET=ON \
    -DHIREDIS_FROM_INTERNET=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${HOME} \
    && make -j$(nproc) \
    && make install -j$(nproc)

# Use ~/.profile instead of ~/.bashrc for non-interactive shell environments
# RUN echo "PATH=${HOME}/bin:${PATH}" >> ~/.profile
ENV PATH=/ccache/build:${PATH}

# Download and install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/miniconda && \
    rm miniconda.sh

# Set environment variables for Miniconda
ENV PATH=/opt/miniconda/bin:${PATH}

# Create a new conda environment
RUN conda init bash \
    && . ~/.bashrc \
    && conda create --name open3d python=3.10 -y && \
    echo "conda activate open3d" >> ~/.bashrc && \
    echo "conda activate open3d" >> ~/.profile

# Download Open3D source code 
RUN cd / && \
    wget https://github.com/isl-org/Open3D/archive/refs/tags/v0.18.0.tar.gz && \
    mkdir Open3D-0.18.0 && \
    tar -xvf v0.18.0.tar.gz && \
    rm v0.18.0.tar.gz

WORKDIR /Open3D-0.18.0

# # Activate the conda environment
SHELL ["conda", "run", "--no-capture-output","-n", "open3d", "/bin/bash", "-c"]

# # Create a build directory (warning: 3090 rtx is hard-coded with that 86)
RUN mkdir build && cd build && \
    cmake .. \
    -DBUILD_CUDA_MODULE=ON \
    -DBUILD_WITH_CUDA_STATIC=ON \
    -DCMAKE_CUDA_ARCHITECTURES=86 \
    -DBUILD_PYTHON_MODULE=ON \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_UNIT_TESTS=OFF \
    -DBUILD_BENCHMARKS=OFF \
    -DBUILD_GUI=ON \
    -DUSE_SYSTEM_GLEW=OFF \
    -DUSE_SYSTEM_GLFW=OFF \
    -DCMAKE_BUILD_TYPE=Release

# # Build Open3D
RUN cd build && make -j$(nproc)

# install python packages in the build directory
RUN cd build && make install-pip-package

# why is this failing? the container, built without this last command, works just fine
# I just need to activate open3d manually and it works
RUN python -c "import open3d"```
