### ISSUE TITLE
Segmentation fault on normal estimation for multiprocessing with pytorch dataloaders

### ISSUE THREAD

**Issue by Parskatt** [isl-org/Open3D#6425]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Estimating normals when using > 0 workers in pytorch dataloaders causes segfaults.

### Steps to reproduce the bug

```python
import torch
import numpy as np
import open3d as o3d


def to_o3d_pcd(pcd):
    pcd_ = o3d.geometry.PointCloud()
    pcd_.points = o3d.utility.Vector3dVector(pcd)
    return pcd_

class SomeData:
    def __len__(self):
        return 100
    def __getitem__(self, idx):
        x = to_o3d_pcd(np.random.randn(1000,3))
        x.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamKNN(knn=33))

if __name__ == "__main__":
    dataset = SomeData()
    dataloader = torch.utils.data.DataLoader(dataset = dataset, num_workers = 1)
    for batch in dataloader:
        print(batch)
```

### Error message

RuntimeError: DataLoader worker (pid 2457484) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ejodhes/edstedt_2023/omnireg/repro.py", line 27, in <module>
    for batch in dataloader:
  File "/home/ejodhes/miniconda3/envs/o3d_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/ejodhes/miniconda3/envs/o3d_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/ejodhes/miniconda3/envs/o3d_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1294, in _get_data
    success, data = self._try_get_data()
  File "/home/ejodhes/miniconda3/envs/o3d_test/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
RuntimeError: DataLoader worker (pid(s) 2457484) exited unexpectedly

### Expected behavior

I expect no segfaults.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04 
- Python version: Python 3.10
- Open3D version: 0.17
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: pip
```

**Comment by Parskatt** [comment]
Possibly related: https://github.com/isl-org/Open3D/issues/1428 , but that issue seems to stem from issues with PCL, and not related to multiprocessing.

**Comment by Parskatt** [comment]
I get the same issues with python 3.8, and also with older versions of open3d (0.13.0)

**Comment by Parskatt** [comment]
Bug seems to only occur with 
```python
multiprocessing_context=multiprocessing.get_context("fork")
```
and not with
```python
multiprocessing_context=multiprocessing.get_context("spawn")
```

**Comment by Parskatt** [comment]
If anyone else is having the same issues, it can be worked around by changing the multiprocessing context, i.e.

```python
import torch
import numpy as np
import open3d as o3d


def to_o3d_pcd(pcd):
    pcd_ = o3d.geometry.PointCloud()
    pcd_.points = o3d.utility.Vector3dVector(pcd)
    return pcd_

class SomeData:
    def __len__(self):
        return 100
    def __getitem__(self, idx):
        x = to_o3d_pcd(np.random.randn(1000,3))
        x.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamKNN(knn=33))
        return np.asarray(x.normals)

if __name__ == "__main__":
    dataset = SomeData()
    dataloader = torch.utils.data.DataLoader(dataset = dataset, num_workers = 1, multiprocessing_context=multiprocessing.get_context("spawn"))
    for batch in dataloader:
        print(batch)
```

**Comment by ssheorey** [comment]
Another option is "forkserver" for python multiprocessing - that can be faster than "spawn".
Closing since this is a Python multiprocessing issue, common to all multi threaded libraries.

**Comment by Parskatt** [comment]
@ssheorey it's been a while, but I'm pretty sure this is due to unconditional OpenMP `num_threads`. I've dealt with similar issues in other places. You likely should put a guard `min(omp_get_max_threads, <whatever current num threads>)` somewhere. It's not a Python multiprocessing issue (it's fork + OpenMP).

EDIT:
Ah, noted you use TBB over OpenMP, then I guess it's a hardcode in that lib rather than OpenMP in this case.
