### ISSUE TITLE
Cannot compile or use pip to install on macOS Sonoma 14.0 - chip Apple M2 Pro

### ISSUE THREAD

**Issue by Christihan-LB** [isl-org/Open3D#6483]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

# Compiled from source:

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D with:
```
mkdir build
cd build
cmake ..
make -j8
```

# Installed with pip:

#### I first install the package with pip:
```
pip install open3d
```
#### Then I import the library:
```
python -W default -c "import open3d as o3d"
```

### Error message

```shell
# Compiled from source:

-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkRuledSurfaceFilter.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkSectorSource.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkSelectEnclosedPoints.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkSelectPolyData.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkSpherePuzzle.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkSpherePuzzleArrows.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkSubdivideTetra.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkTrimmedExtrusionFilter.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkVolumeOfRevolutionFilter.h
-- Installing: /Users/claurelb/Open3D/build/vtk/include/vtk-9.1/vtkFiltersModelingModule.h
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/libvtkFiltersModeling-9.1.a
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/VTK-targets.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/VTK-targets-release.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/VTK-vtk-module-properties.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/Finddouble-conversion.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindEigen3.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindEXPAT.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindExprTk.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindFFMPEG.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindFontConfig.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindFreetype.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindGL2PS.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindGLEW.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindJOGL.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindJsonCpp.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindLibHaru.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindLibPROJ.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindLibXml2.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindLZ4.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindLZMA.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/Findmpi4py.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindMySQL.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindNetCDF.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindODBC.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindOGG.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindOpenSlide.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindOpenVR.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindOSMesa.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindPEGTL.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindSDL2.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindTBB.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindTHEORA.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/Findutf8cpp.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/FindCGNS.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkCMakeBackports.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkDetectLibraryType.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkEncodeString.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkHashSource.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkModule.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkModuleGraphviz.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkModuleJson.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkModuleTesting.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkModuleWrapJava.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkModuleWrapPython.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkObjectFactory.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkObjectFactory.cxx.in
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkObjectFactory.h.in
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkTestingDriver.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkTestingRenderingDriver.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtkTopologicalSort.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtk-use-file-compat.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtk-use-file-deprecated.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtk-use-file-error.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.13/FindZLIB.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.16/FindPostgreSQL.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.18/FindPython/Support.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.18/FindPython2.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.18/FindPython3.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.19/FindJPEG.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.19/FindLibArchive.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.19/FindSQLite3.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.19/FindX11.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.20/FindGDAL.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI/fortranparam_mpi.f90.in
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI/libver_mpi.c
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI/libver_mpi.f90.in
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI/mpiver.f90.in
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI/test_mpi.c
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI/test_mpi.f90.in
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/3.22/FindMPI.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/99/FindHDF5.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/patches/99/FindOpenGL.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtk-config.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtk-config-version.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/vtk-prefix.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/lib/cmake/vtk-9.1/VTK-vtk-module-find-packages.cmake
-- Installing: /Users/claurelb/Open3D/build/vtk/share/licenses/VTK/Copyright.txt
[ 34%] Completed 'ext_vtk'
[ 34%] Built target ext_vtk
make: *** [all] Error 2

---------------------------------------------------------------------------------------------
# Installed with pip:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/claurelb/anaconda3/envs/coslam/lib/python3.8/site-packages/open3d/__init__.py", line 93, in <module>
    from open3d.cpu.pybind import (core, camera, data, geometry, io, pipelines,
ImportError: dlopen(/Users/claurelb/anaconda3/envs/coslam/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/libomp/lib/libomp.dylib
  Referenced from: <A2C68595-9594-3758-BEFB-86BA2C701093> /Users/claurelb/anaconda3/envs/coslam/lib/python3.8/site-packages/open3d/cpu/pybind.cpython-38-darwin.so
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file, not in dyld cache)
```

### Open3D, Python and System information

```markdown
- Operating system: macOS 14.0
- Python version: Python 3.8 [Clang 14.0.6] :: Anaconda, Inc. on darwin
- Open3D version: Compiled from source
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: build from source and pip
- Compiler version (if built from source): Clang 14.0.6
```

**Comment by saurabheights** [comment]
When your make is failing, why you are trying to do pip install. See above logs - 

```
[ 34%] Built target ext_vtk
make: *** [all] Error 2
```

**Comment by Christihan-LB** [comment]
It was in two different moments. I found the solution to my problem after installing with pip in this comment https://github.com/isl-org/Open3D/issues/5655#issuecomment-1334148643.

**Comment by valkovich** [comment]
But the problem still exist. I think it was too early to close this
