### ISSUE TITLE
Jupyter notebook kernel crashes when I exit the visualization window

### ISSUE THREAD

**Issue by kwhuang88228** [isl-org/Open3D#6596]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

My Jupyter notebook kernel crashes when I exit the visualization window, forcing me to force-quit the application and rerun the notebook every time I exit a visualization. I've tested my setup with Python 3.8.18 and 3.11.7, both with the same failure.

### Steps to reproduce the bug

```python
import open3d as o3d
import os

pcd = o3d.io.read_point_cloud("data/fragment.ply")
o3d.visualization.draw_geometries([pcd])
```

### Error message

The kernel 'open3d (Python 3.11.7)' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

11:23:38.791 [info] Handle Execution of Cells 0 for ~/Documents/research/code/Open3D/python/scratch/scratch.ipynb
11:23:38.800 [info] Kernel acknowledged execution of cell 0 @ 1704990218800
11:23:40.411 [info] End cell 0 execution after 1.611s, completed @ 1704990220411, started @ 1704990218800
11:23:43.549 [info] Handle Execution of Cells 2 for ~/Documents/research/code/Open3D/python/scratch/scratch.ipynb
11:23:43.554 [info] Kernel acknowledged execution of cell 2 @ 1704990223554
11:23:47.047 [info] End cell 2 execution after 3.493s, completed @ 1704990227047, started @ 1704990223554
11:23:52.516 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 
11:23:52.516 [info] Dispose Kernel process 99097.
11:23:52.518 [error] Jupyter Extension (Error in onKernelStatusChanged, method:onKernelStatusChanged): [Error: notebook controller is DISPOSED
	at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:92921)
	at r.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:129:2129)
	at r.getOrCreate (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:129:1897)
	at fp (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:132:2394)
	at ef.endCellAndDisplayErrorsInCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:235:50171)
	at ef.onKernelStatusChanged (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:235:49765)
	at n.value (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:80:11251)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at by.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:251:2465)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at t (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:235:75179)
	at D (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:20395)
	at Object.d [as emit] (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:20048)
	at i.emit (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:18131)
	at ZT.onStatusChanged (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:235:34053)
	at D (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:20395)
	at Object.d [as emit] (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:20048)
	at i.emit (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:18131)
	at a_.onKernelStatus (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:264:23662)
	at D (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:20395)
	at Object.d [as emit] (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:20048)
	at i.emit (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:40:18131)
	at s_.shutdown (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1100101639-darwin-arm64/dist/extension.node.js:264:15519)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]

### Open3D, Python and System information

```markdown
- Operating system: macOS 14.2.1
- Python version: Python 3.8.18, 3.11.7
- Open3D version: 0.18.0
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by saurabheights** [comment]
@kwhuang88228 See https://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html

For jupyter, use web_visualizer module.

**Comment by kwhuang88228** [comment]
Got it thanks!

**Comment by kwhuang88228** [comment]
Got it thanks!

**Comment by lucas4at** [comment]
@saurabheights I have the same issue as @kwhuang88228 but when I try:

```
import open3d as o3d
from open3d.web_visualizer import draw
```

I'm receiving:

```
RuntimeError: Open3D WebVisualizer Jupyter extension is not available. To use WebVisualizer, build Open3D with -DBUILD_JUPYTER_EXTENSION=ON.
```

Although it says: "Open3D official Python wheels come with Jupyter web visualizer support" in the link you mention.

I am using Python 3.10.13 and have open3d version 0.18.0 installed through pip.

I tried to uninstall through pip and instead use conda, but running:

```
conda install open3d-admin::open3d
```

returns a `PackagesNotFoundError`. 

Any ideas?

**Comment by saurabheights** [comment]
I am unable to reproduce the issue. This is what I tried.

```
conda create --name test1 python=3.10
conda activate test1
pip install open3d  # This installed open3d 0.18.0
python3 -c "import open3d as o3d; from open3d.web_visualizer import draw"  # Runs fine

pip install jupyter notebook
cd Open3D/docs/tutorial/visualization
jupyter notebook
# Run jupyter_visualization.ipynb
```

![image](https://github.com/isl-org/Open3D/assets/11634769/f317ec30-cdfc-4f76-a3ac-de1dc64749b4)

Dont use conda. AFAIK, open3d only releases pip wheels.

**Comment by lucas4at** [comment]
Thanks so much for your quick reply @saurabheights.

Just tested:

```
conda create --name test1 python=3.10
conda activate test1
pip install open3d  # This indeed installed open3d 0.18.0 in my case as well
python3 -c "import open3d as o3d; from open3d.web_visualizer import draw"
```
returns 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lucasvanwalstijn/miniconda3/envs/test1/lib/python3.10/site-packages/open3d/web_visualizer.py", line 8, in <module>
    import ipywidgets
ModuleNotFoundError: No module named 'ipywidgets'
```

Which probably makes sense since jupyter is not yet installed.

If I then 

```
pip install jupyter notebook
```

and rerun

```
python3 -c "import open3d as o3d; from open3d.web_visualizer import draw"
```

I'm getting 

```
[Open3D INFO] Resetting default logger to print to terminal.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lucasvanwalstijn/miniconda3/envs/test1/lib/python3.10/site-packages/open3d/web_visualizer.py", line 19, in <module>
    raise RuntimeError(
RuntimeError: Open3D WebVisualizer Jupyter extension is not available. To use WebVisualizer, build Open3D with -DBUILD_JUPYTER_EXTENSION=ON.
```

I'm working on a Mac with M2, could that have anything to do with it?

**Comment by saurabheights** [comment]
@lucas4at Sorry, can't help on issue related with Mac. I don't have one for now. 

@kwhuang88228 What are the warning messages? I only see INFO ones.

**Comment by kwhuang88228** [comment]
Sorry I meant INFO messages.

**Comment by iegorval** [comment]
> @kwhuang88228 See https://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html
> 
> For jupyter, use web_visualizer module.

Is there actually any normal documentation for this module? Sorry, but it is difficult to use something that seems completely undocumented (except for a brief mention at https://www.open3d.org/docs/latest/tutorial/visualization/web_visualizer.html).
