### ISSUE TITLE
Cannot import Open3D0.18 on Windows 11 64

### ISSUE THREAD

**Issue by mfbush** [isl-org/Open3D#6749]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Steps to reproduce the issue

From Anaconda Prompt
`conda create -n test_env python=3.11`
`conda activate test_env`
`pip install open3d`
`python -c "import open3d as o3d; print(o3d.__version__)"`

### Error message

```shell
From Anaconda Prompt:
(test_env) C:\Users\mattb>python -c "import open3d as o3d; print(o3d.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mattb\anaconda3\envs\mobilemesh_env\Lib\site-packages\open3d\__init__.py", line 93, in <module>
    from open3d.cpu.pybind import (core, camera, data, geometry, io, pipelines,
ImportError: DLL load failed while importing pybind: The specified module could not be found.

```

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 Pro N for Workstations
- Python version: Python 3.11.8
- Open3D version: output from python raises error; Conda list reports version 0.18.
- System architecture: x86
- Is this a remote workstation?: yes (error raised in local and remote sessions)
- How did you install Open3D?: pip
- Compiler version (if built from source): n/a
```

### Additional information

I just set up this PC. This is the only Python library that has raised an error for me.
Reproduced with Python 3.10 and 3.11
Reproduced with Open3d 0.17, 0.18 (main), and 0.18 (development via "pip install -U -f https://www.open3d.org/docs/latest/getting_started.html open3d").
Tried uninstalling Anaconda, CUDA, and Visual Studio, then reinstalling CUDA, then Visual Studio, and then Anaconda. No change.

**Comment by mfbush** [comment]
Example, including install of 0.18 development and attempt to import.

> (test_env) C:\Users\mattb\Desktop>pip install -U -f https://www.open3d.org/docs/latest/getting_started.html open3d
> Looking in links: https://www.open3d.org/docs/latest/getting_started.html
> Collecting open3d
>   Using cached https://storage.googleapis.com/open3d-releases/python-wheels/open3d-0.18.0%2B80ae047-cp311-cp311-win_amd64.whl (63.8 MB)
> Requirement already satisfied: numpy>=1.18.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from open3d) (1.26.4)
> Requirement already satisfied: dash>=2.6.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from open3d) (2.16.1)
> Requirement already satisfied: werkzeug>=2.2.3 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from open3d) (3.0.2)
> Requirement already satisfied: nbformat>=5.7.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from open3d) (5.10.4)
> Requirement already satisfied: configargparse in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from open3d) (1.7)
> Requirement already satisfied: ipywidgets>=8.0.4 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from open3d) (8.1.2)
> Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (3.0.3)
> Requirement already satisfied: plotly>=5.0.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (5.20.0)
> Requirement already satisfied: dash-html-components==2.0.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (2.0.0)
> Requirement already satisfied: dash-core-components==2.0.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (2.0.0)
> Requirement already satisfied: dash-table==5.0.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (5.0.0)
> Requirement already satisfied: importlib-metadata in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (7.1.0)
> Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (4.11.0)
> Requirement already satisfied: requests in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (2.31.0)
> Requirement already satisfied: retrying in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (1.3.4)
> Requirement already satisfied: nest-asyncio in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (1.6.0)
> Requirement already satisfied: setuptools in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from dash>=2.6.0->open3d) (68.2.2)
> Requirement already satisfied: comm>=0.1.3 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipywidgets>=8.0.4->open3d) (0.2.2)
> Requirement already satisfied: ipython>=6.1.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipywidgets>=8.0.4->open3d) (8.23.0)
> Requirement already satisfied: traitlets>=4.3.1 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipywidgets>=8.0.4->open3d) (5.14.2)
> Requirement already satisfied: widgetsnbextension~=4.0.10 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipywidgets>=8.0.4->open3d) (4.0.10)
> Requirement already satisfied: jupyterlab-widgets~=3.0.10 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipywidgets>=8.0.4->open3d) (3.0.10)
> Requirement already satisfied: fastjsonschema>=2.15 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from nbformat>=5.7.0->open3d) (2.19.1)
> Requirement already satisfied: jsonschema>=2.6 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from nbformat>=5.7.0->open3d) (4.21.1)
> Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from nbformat>=5.7.0->open3d) (5.7.2)
> Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from werkzeug>=2.2.3->open3d) (2.1.5)
> Requirement already satisfied: Jinja2>=3.1.2 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.6.0->open3d) (3.1.3)
> Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.6.0->open3d) (2.1.2)
> Requirement already satisfied: click>=8.1.3 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.6.0->open3d) (8.1.7)
> Requirement already satisfied: blinker>=1.6.2 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.6.0->open3d) (1.7.0)
> Requirement already satisfied: decorator in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (5.1.1)
> Requirement already satisfied: jedi>=0.16 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.19.1)
> Requirement already satisfied: matplotlib-inline in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.1.6)
> Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (3.0.43)
> Requirement already satisfied: pygments>=2.4.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (2.17.2)
> Requirement already satisfied: stack-data in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.6.3)
> Requirement already satisfied: colorama in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.4.6)
> Requirement already satisfied: attrs>=22.2.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7.0->open3d) (23.2.0)
> Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7.0->open3d) (2023.12.1)
> Requirement already satisfied: referencing>=0.28.4 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7.0->open3d) (0.34.0)
> Requirement already satisfied: rpds-py>=0.7.1 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7.0->open3d) (0.18.0)
> Requirement already satisfied: platformdirs>=2.5 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=5.7.0->open3d) (4.2.0)
> Requirement already satisfied: pywin32>=300 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=5.7.0->open3d) (306)
> Requirement already satisfied: tenacity>=6.2.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from plotly>=5.0.0->dash>=2.6.0->open3d) (8.2.3)
> Requirement already satisfied: packaging in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from plotly>=5.0.0->dash>=2.6.0->open3d) (24.0)
> Requirement already satisfied: zipp>=0.5 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from importlib-metadata->dash>=2.6.0->open3d) (3.18.1)
> Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from requests->dash>=2.6.0->open3d) (3.3.2)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from requests->dash>=2.6.0->open3d) (3.6)
> Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from requests->dash>=2.6.0->open3d) (2.2.1)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from requests->dash>=2.6.0->open3d) (2024.2.2)
> Requirement already satisfied: six>=1.7.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from retrying->dash>=2.6.0->open3d) (1.16.0)
> Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.8.4)
> Requirement already satisfied: wcwidth in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.2.13)
> Requirement already satisfied: executing>=1.2.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (2.0.1)
> Requirement already satisfied: asttokens>=2.1.0 in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (2.4.1)
> Requirement already satisfied: pure-eval in c:\users\mattb\anaconda3\envs\test_env\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=8.0.4->open3d) (0.2.2)
> Installing collected packages: open3d
> Successfully installed open3d-0.18.0+80ae047
> 
> (test_env) C:\Users\mattb\Desktop>python -c "import open3d as o3d; print(o3d.__version__)"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\mattb\anaconda3\envs\test_env\Lib\site-packages\open3d\__init__.py", line 93, in <module>
>     from open3d.cpu.pybind import (core, camera, data, geometry, io, pipelines,
> ImportError: DLL load failed while importing pybind: The specified module could not be found.

**Comment by mfbush** [comment]
**Solution:** I installed the Media Feature Pack for Windows 11, which is not installed by defaults in Windows 11 Pro N for Workstations. I am now able to load Open3D.
`(test_env) C:\Users\mattb>python -c "import open3d as o3d; print(o3d.__version__)"`
`0.18.0+80ae047`
**Ask:** I recommend the addition of more verbose error text, including the specific names of DLL modules that could not be found. The original message did not give me much to work with.
`ImportError: DLL load failed while importing pybind: The specified module could not be found.`
