### ISSUE TITLE
open3d initialization failed Prompt:UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4-5: invalid continuation byte

### ISSUE THREAD

**Issue by 979602732** [isl-org/Open3D#6756]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Steps to reproduce the issue

cmake --build . --config Release --target ALL_BUILD
cmake --build . --config Release --target INSTALL
cmake --build . --config Release --target install-pip-package
python -c "import open3d; print(open3d)"

### Error message

```shell
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4-5: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\anaconda3\lib\site-packages\open3d\__init__.py", line 73, in <module>
    from open3d.cuda.pybind import (core, camera, data, geometry, io,
ImportError: initialization failed
python-BaseException
[Open3D INFO] Memory Statistics: (Device) (#Malloc) (#Free)
[Open3D INFO] ---------------------------------------------
[Open3D WARNING] CPU:0: 9 7 --> 2 with 256 total bytes
[Open3D WARNING]     0x181b34c31b0 @ 128 bytes
[Open3D WARNING]     0x181b34c7260 @ 128 bytes
[Open3D INFO] ---------------------------------------------

Process finished with exit code 1
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit  cuda 11.8 
- Python version: Python 3.10
- Open3D version: 0.18
- System architecture: x86 
- Is this a remote workstation: no
- How did you install Open3D: build from source
- Compiler version (if built from source):VS2019
```

### Additional information

![image](https://github.com/isl-org/Open3D/assets/75673127/8347c010-41dc-45a1-9d2d-8b3574a717ee)

**Comment by FishWoWater** [comment]
same issue with me

**Comment by snow1y** [comment]
I met the same issue. I tried the way in #6277, but it didn't work. Can anybody solve this problem?

**Comment by snow1y** [comment]
I finally avoid this problem by changing open3D version to 0.17.0 and changing python version to 3.9. Instead of 'utf-8' codec can't decode bytes in position 4-5: invalid continuation byte' I met before, I met the UnicodeDecodeError in #6277. And then I used the way in #6277, finally it worked.

**Comment by 979602732** [comment]
When I switched to version 0.17 it also compiled and installed fine, but
the bug still exists in version 0.18

**Comment by luomingcheng** [comment]
> I finally avoid this problem by changing open3D version to 0.17.0 and changing python version to 3.9. Instead of 'utf-8' codec can't decode bytes in position 4-5: invalid continuation byte' I met before, I met the UnicodeDecodeError in #6277. And then I used the way in #6277, finally it worked.

I also successfully compiled version 0.17.0 using this method~
