### ISSUE TITLE
Crash on construction of `o3d.visualization.VisualizerWithEditing`

### ISSUE THREAD

**Issue by kylevedder** [isl-org/Open3D#6888]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

Creating a `o3d.visualization.VisualizerWithEditing()` triggers a pybind error

### Steps to reproduce the bug

On latest development release (and official 0.18.0 release):

```python
import open3d as o3d
print(o3d.__version__)
vis = o3d.visualization.VisualizerWithEditing()
```

### Error message

```
0.18.0+90810a3
Traceback (most recent call last):
  File "/bucketed_scene_flow_eval/o3d_edit_tests.py", line 25, in <module>
    vis = CustomVisualizerWithEditing()
  File "/bucketed_scene_flow_eval/o3d_edit_tests.py", line 11, in __init__
    super().__init__()
TypeError: pybind11::init(): unable to convert returned instance to required alias class: no `Alias<Class>(Class &&)` constructor available
```

### Expected behavior

It doesn't crash

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 20.04.04 / macOS 10.15 / Windows 10 64-bit
- Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
- Open3D version: 0.18.0
- System architecture: x86 
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

**Comment by kylevedder** [comment]
This seems to have been broken since at least `0.16.0`

**Comment by kylevedder** [comment]
Weirdly this appears to have been caused by something in my path
