### ISSUE TITLE
GPU use on Windows

### ISSUE THREAD

**Issue by Sippi99** [isl-org/Open3D#7002]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### Then, I build Open3D (on Windows 10 64-bit, with CUDA 11.0, PIP 24.0) with:
```
python -m venv .venv
.venv\scripts\activate
pip install -r docs/requirements.txt
mkdir build
cd build
cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX="C:/Users/Name/Open3D/install/" -DBUILD_CUDA_MODULE=ON ..

cmake --build . --config Release --target ALL_BUILD

cmake --build . --config Release --target INSTALL

:: Install pip package in the current python environment
cmake --build . --config Release --target install-pip-package

:: Create Python package in build/lib
cmake --build . --config Release --target python-package

:: Create pip package in build/lib
:: This creates a .whl file that you can install manually.
cmake --build . --config Release --target pip-package
```
####After the build I installed the created pip-package in my venv of my projekt 

```
cd path\to\my\projekt
.venv\scripts\activate
pip install C:\Users\XXX\Open3D\build\lib\python_package\pip_package\open3d-0.18.0+5f148f2fd-cp39-cp39-win_amd64.whl

python -c "import open3d as o3d; print(o3d.core.cuda.is_available())"


### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XXX\XXX\XXX\XXX\.venv\lib\site-packages\open3d\__init__.py", line 101, in <module>
    from open3d.cpu.pybind import (
ModuleNotFoundError: No module named 'open3d.cpu'
```

### Open3D, Python and System information

```markdown
- Operating system: Windows 10 64-bit
- Python version: Python 3.9
- Open3D version: 0.18.0
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip / build from source
- Compiler version (if built from source): Visual Studio 16 2019
```

**Comment by leopardyao** [comment]
similar issue here. and also in homepage it seems pip install can already do the cuda connection but now it seems even compiling does not help. without being able to use Cuda  resource it is a kinda of disappointed.

**Comment by asdiujvaosidujdposiadjapoij** [comment]
In Windows 11, I was able to make it work, I think. If I understand correctly, the .pyd file of the Open3d bindings, located in my machine at `C:\Users\asdiujvaosidujdposiadjapoij\AppData\Local\Programs\Python\Python312\Lib\site-packages\open3d\cuda` depends on `tbb12.dll`. Even though `tbb12.dll` is in the python open3d installation path, it was not found. so what is did was putting `tbb12.dll` in the default library path, in my machine being `C:/Windows/System32`. 

Now it works, though I hope there's a cleaner solution, one which does not involve putting binaries in system folders.
